# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: compat/v1/workflow.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'compat/v1/workflow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63ompat/v1/workflow.proto\x12\tcompat.v1\"Z\n\nRunRequest\x12\x1f\n\x0bworkflow_id\x18\x01 \x01(\tR\nworkflowId\x12\x15\n\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x14\n\x05value\x18\x03 \x01(\tR\x05value\"?\n\x0bRunResponse\x12\x14\n\x05value\x18\x01 \x01(\tR\x05value\x12\x1a\n\x08replayed\x18\x02 \x01(\x08R\x08replayed2G\n\x0fWorkflowService\x12\x34\n\x03Run\x12\x15.compat.v1.RunRequest\x1a\x16.compat.v1.RunResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compat.v1.workflow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNREQUEST']._serialized_start=39
  _globals['_RUNREQUEST']._serialized_end=129
  _globals['_RUNRESPONSE']._serialized_start=131
  _globals['_RUNRESPONSE']._serialized_end=194
  _globals['_WORKFLOWSERVICE']._serialized_start=196
  _globals['_WORKFLOWSERVICE']._serialized_end=267
# @@protoc_insertion_point(module_scope)
