# Generated from temporaless/v1/inspection.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "protobuf=google,io=async".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint
from pyqwest import Client

from .inspection_pb2 import DescribeRunRequest, DescribeRunResponse, GetInspectionCapabilitiesRequest, GetInspectionCapabilitiesResponse, ListNamespacesRequest, ListNamespacesResponse, ListScheduledWakesRequest, ListScheduledWakesResponse, ListWorkflowDirectoryRequest, ListWorkflowDirectoryResponse, ListWorkflowRunsRequest, ListWorkflowRunsResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class RunInspectionService(Protocol):
    """
    RunInspectionService is the read-only projection of one or more registered
    record stores. No method writes, repairs, claims, or deletes, so a server
    can run with read-only bucket credentials. Listings are bounded per request
    and continue through opaque page tokens; implementations must refuse work
    past their advertised bounds instead of silently truncating.
    """
    async def get_inspection_capabilities(self, request: GetInspectionCapabilitiesRequest, ctx: RequestContext[GetInspectionCapabilitiesRequest, GetInspectionCapabilitiesResponse], /) -> GetInspectionCapabilitiesResponse:
        """
        Report the stores the caller may inspect and what each can answer.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_namespaces(self, request: ListNamespacesRequest, ctx: RequestContext[ListNamespacesRequest, ListNamespacesResponse], /) -> ListNamespacesResponse:
        """
        Report the store's configured namespaces and whether each holds records.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_workflow_directory(self, request: ListWorkflowDirectoryRequest, ctx: RequestContext[ListWorkflowDirectoryRequest, ListWorkflowDirectoryResponse], /) -> ListWorkflowDirectoryResponse:
        """
        List one row per workflow_id in a namespace from the latest-run pointers,
        with derived pending state for runs that are still in progress.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_workflow_runs(self, request: ListWorkflowRunsRequest, ctx: RequestContext[ListWorkflowRunsRequest, ListWorkflowRunsResponse], /) -> ListWorkflowRunsResponse:
        """
        List the runs of one workflow_id, ordered by run_id. Run IDs are opaque
        to Temporaless; the order is lexical, never interpreted.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_scheduled_wakes(self, request: ListScheduledWakesRequest, ctx: RequestContext[ListScheduledWakesRequest, ListScheduledWakesResponse], /) -> ListScheduledWakesResponse:
        """
        List scheduled wakes from the due-timer ledger. Reports disagreement
        between the ledger and canonical timer records; never repairs it.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def describe_run(self, request: DescribeRunRequest, ctx: RequestContext[DescribeRunRequest, DescribeRunResponse], /) -> DescribeRunResponse:
        """
        Describe one run: its durable records plus derived history and pending
        state.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class RunInspectionServiceASGIApplication(ConnectASGIApplication[RunInspectionService]):
    def __init__(
        self,
        service: RunInspectionService | AsyncGenerator[RunInspectionService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/temporaless.v1.RunInspectionService/GetInspectionCapabilities": Endpoint.unary(
                    method=MethodInfo(
                        name="GetInspectionCapabilities",
                        service_name="temporaless.v1.RunInspectionService",
                        input=GetInspectionCapabilitiesRequest,
                        output=GetInspectionCapabilitiesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_inspection_capabilities,
                ),
                "/temporaless.v1.RunInspectionService/ListNamespaces": Endpoint.unary(
                    method=MethodInfo(
                        name="ListNamespaces",
                        service_name="temporaless.v1.RunInspectionService",
                        input=ListNamespacesRequest,
                        output=ListNamespacesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_namespaces,
                ),
                "/temporaless.v1.RunInspectionService/ListWorkflowDirectory": Endpoint.unary(
                    method=MethodInfo(
                        name="ListWorkflowDirectory",
                        service_name="temporaless.v1.RunInspectionService",
                        input=ListWorkflowDirectoryRequest,
                        output=ListWorkflowDirectoryResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_workflow_directory,
                ),
                "/temporaless.v1.RunInspectionService/ListWorkflowRuns": Endpoint.unary(
                    method=MethodInfo(
                        name="ListWorkflowRuns",
                        service_name="temporaless.v1.RunInspectionService",
                        input=ListWorkflowRunsRequest,
                        output=ListWorkflowRunsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_workflow_runs,
                ),
                "/temporaless.v1.RunInspectionService/ListScheduledWakes": Endpoint.unary(
                    method=MethodInfo(
                        name="ListScheduledWakes",
                        service_name="temporaless.v1.RunInspectionService",
                        input=ListScheduledWakesRequest,
                        output=ListScheduledWakesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_scheduled_wakes,
                ),
                "/temporaless.v1.RunInspectionService/DescribeRun": Endpoint.unary(
                    method=MethodInfo(
                        name="DescribeRun",
                        service_name="temporaless.v1.RunInspectionService",
                        input=DescribeRunRequest,
                        output=DescribeRunResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.describe_run,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/temporaless.v1.RunInspectionService"


class RunInspectionServiceClient(ConnectClient):
    """
    RunInspectionService is the read-only projection of one or more registered
    record stores. No method writes, repairs, claims, or deletes, so a server
    can run with read-only bucket credentials. Listings are bounded per request
    and continue through opaque page tokens; implementations must refuse work
    past their advertised bounds instead of silently truncating.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def get_inspection_capabilities(
        self,
        request: GetInspectionCapabilitiesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetInspectionCapabilitiesResponse:
        """
        Report the stores the caller may inspect and what each can answer.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetInspectionCapabilities",
                service_name="temporaless.v1.RunInspectionService",
                input=GetInspectionCapabilitiesRequest,
                output=GetInspectionCapabilitiesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_namespaces(
        self,
        request: ListNamespacesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListNamespacesResponse:
        """
        Report the store's configured namespaces and whether each holds records.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListNamespaces",
                service_name="temporaless.v1.RunInspectionService",
                input=ListNamespacesRequest,
                output=ListNamespacesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_workflow_directory(
        self,
        request: ListWorkflowDirectoryRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListWorkflowDirectoryResponse:
        """
        List one row per workflow_id in a namespace from the latest-run pointers,
        with derived pending state for runs that are still in progress.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListWorkflowDirectory",
                service_name="temporaless.v1.RunInspectionService",
                input=ListWorkflowDirectoryRequest,
                output=ListWorkflowDirectoryResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_workflow_runs(
        self,
        request: ListWorkflowRunsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListWorkflowRunsResponse:
        """
        List the runs of one workflow_id, ordered by run_id. Run IDs are opaque
        to Temporaless; the order is lexical, never interpreted.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListWorkflowRuns",
                service_name="temporaless.v1.RunInspectionService",
                input=ListWorkflowRunsRequest,
                output=ListWorkflowRunsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_scheduled_wakes(
        self,
        request: ListScheduledWakesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListScheduledWakesResponse:
        """
        List scheduled wakes from the due-timer ledger. Reports disagreement
        between the ledger and canonical timer records; never repairs it.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListScheduledWakes",
                service_name="temporaless.v1.RunInspectionService",
                input=ListScheduledWakesRequest,
                output=ListScheduledWakesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def describe_run(
        self,
        request: DescribeRunRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> DescribeRunResponse:
        """
        Describe one run: its durable records plus derived history and pending
        state.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DescribeRun",
                service_name="temporaless.v1.RunInspectionService",
                input=DescribeRunRequest,
                output=DescribeRunResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
