# Generated from temporaless/v1/temporaless.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "protobuf=google,io=async".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint
from pyqwest import Client

from .temporaless_pb2 import DeleteActivityRequest, DeleteActivityResponse, DeleteClaimRequest, DeleteClaimResponse, DeleteEventRequest, DeleteEventResponse, DeleteRunRequest, DeleteRunResponse, DeleteTimerRequest, DeleteTimerResponse, DeleteWorkflowRequest, DeleteWorkflowResponse, DeliverEventRequest, DeliverEventResponse, DueTimersRequest, DueTimersResponse, GetActivityRequest, GetActivityResponse, GetClaimRequest, GetClaimResponse, GetEventRequest, GetEventResponse, GetLatestWorkflowRunRequest, GetLatestWorkflowRunResponse, GetStoreCapabilitiesRequest, GetStoreCapabilitiesResponse, GetTimerRequest, GetTimerResponse, GetWorkflowRequest, GetWorkflowResponse, ListActivitiesRequest, ListActivitiesResponse, ListClaimsRequest, ListClaimsResponse, ListEventsRequest, ListEventsResponse, ListTimersRequest, ListTimersResponse, ListWorkflowsRequest, ListWorkflowsResponse, PutActivityRequest, PutActivityResponse, PutEventRequest, PutEventResponse, PutTimerRequest, PutTimerResponse, PutWorkflowRequest, PutWorkflowResponse, RecordQueryServiceDueTimersRequest, RecordQueryServiceDueTimersResponse, RecordQueryServiceListActivitiesRequest, RecordQueryServiceListActivitiesResponse, SweepRequest, SweepResponse, TryCreateClaimRequest, TryCreateClaimResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class RecordStoreService(Protocol):
    """
    RecordStoreService is the cross-language core durability contract.

    Every record kind (workflow, activity, timer, event, claim) supports
    point Get/Put/Delete. Activity, timer, event, and claim lists are scoped to
    a single workflow run for replay prefetch and run deletion. Cross-run search
    lives on RecordQueryService.

    Bucket/file backends implement this surface directly without SQL.
    """
    async def get_store_capabilities(self, request: GetStoreCapabilitiesRequest, ctx: RequestContext[GetStoreCapabilitiesRequest, GetStoreCapabilitiesResponse], /) -> GetStoreCapabilitiesResponse:
        """
        Report what the configured store can do (claim coordination tier, etc.).
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_workflow(self, request: GetWorkflowRequest, ctx: RequestContext[GetWorkflowRequest, GetWorkflowResponse], /) -> GetWorkflowResponse:
        """
        Read a single workflow record by key.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def put_workflow(self, request: PutWorkflowRequest, ctx: RequestContext[PutWorkflowRequest, PutWorkflowResponse], /) -> PutWorkflowResponse:
        """
        Write or replace a single workflow record.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_latest_workflow_run(self, request: GetLatestWorkflowRunRequest, ctx: RequestContext[GetLatestWorkflowRunRequest, GetLatestWorkflowRunResponse], /) -> GetLatestWorkflowRunResponse:
        """
        Read the derived latest-run pointer for one workflow_id.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_timer(self, request: GetTimerRequest, ctx: RequestContext[GetTimerRequest, GetTimerResponse], /) -> GetTimerResponse:
        """
        Read a single durable timer record by key.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def put_timer(self, request: PutTimerRequest, ctx: RequestContext[PutTimerRequest, PutTimerResponse], /) -> PutTimerResponse:
        """
        Write or replace a single timer record.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_activity(self, request: GetActivityRequest, ctx: RequestContext[GetActivityRequest, GetActivityResponse], /) -> GetActivityResponse:
        """
        Read a single activity record by key.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def put_activity(self, request: PutActivityRequest, ctx: RequestContext[PutActivityRequest, PutActivityResponse], /) -> PutActivityResponse:
        """
        Write or replace a single activity record.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_claim(self, request: GetClaimRequest, ctx: RequestContext[GetClaimRequest, GetClaimResponse], /) -> GetClaimResponse:
        """
        Read a single coordination claim by key.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def try_create_claim(self, request: TryCreateClaimRequest, ctx: RequestContext[TryCreateClaimRequest, TryCreateClaimResponse], /) -> TryCreateClaimResponse:
        """
        Write a claim only if none already exists at the key. Returns
        `created=false` when the key is taken. Core workflow, activity, and
        concurrency coordination treats every existing claim as busy, including
        one with the same owner_id.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_claim(self, request: DeleteClaimRequest, ctx: RequestContext[DeleteClaimRequest, DeleteClaimResponse], /) -> DeleteClaimResponse:
        """
        Idempotently release a claim. Used for workflow-execution, activity, and
        concurrency claims at durable/orderly boundaries; safe when the key is
        absent.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_event(self, request: GetEventRequest, ctx: RequestContext[GetEventRequest, GetEventResponse], /) -> GetEventResponse:
        """
        Read a single signal/event record by key.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def put_event(self, request: PutEventRequest, ctx: RequestContext[PutEventRequest, PutEventResponse], /) -> PutEventResponse:
        """
        Deliver a signal payload to a waiting workflow. External services
        that intentionally need replace semantics may call this low-level point
        write. Prefer DeliverEvent for create-once external delivery.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def deliver_event(self, request: DeliverEventRequest, ctx: RequestContext[DeliverEventRequest, DeliverEventResponse], /) -> DeliverEventResponse:
        """
        Atomically establish the first payload for an EventKey. An identical
        duplicate is idempotent; a different payload fails with
        FAILED_PRECONDITION. Backends without conditional creation reject the
        operation rather than emulating it with check-then-write.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_activities(self, request: ListActivitiesRequest, ctx: RequestContext[ListActivitiesRequest, ListActivitiesResponse], /) -> ListActivitiesResponse:
        """
        List all activity records under a single workflow run.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_timers(self, request: ListTimersRequest, ctx: RequestContext[ListTimersRequest, ListTimersResponse], /) -> ListTimersResponse:
        """
        List timer records under a single workflow run, optionally filtered by status.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_events(self, request: ListEventsRequest, ctx: RequestContext[ListEventsRequest, ListEventsResponse], /) -> ListEventsResponse:
        """
        List event records under a single workflow run.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_claims(self, request: ListClaimsRequest, ctx: RequestContext[ListClaimsRequest, ListClaimsResponse], /) -> ListClaimsResponse:
        """
        List coordination claims under a single workflow run. This is the narrow
        run-deletion seam, not a cross-run query API.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_workflow(self, request: DeleteWorkflowRequest, ctx: RequestContext[DeleteWorkflowRequest, DeleteWorkflowResponse], /) -> DeleteWorkflowResponse:
        """
        Idempotently remove a workflow record only.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_activity(self, request: DeleteActivityRequest, ctx: RequestContext[DeleteActivityRequest, DeleteActivityResponse], /) -> DeleteActivityResponse:
        """
        Idempotently remove an activity record so the next `ExecuteActivity`
        re-executes the activity body.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_timer(self, request: DeleteTimerRequest, ctx: RequestContext[DeleteTimerRequest, DeleteTimerResponse], /) -> DeleteTimerResponse:
        """
        Idempotently remove a timer record.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_event(self, request: DeleteEventRequest, ctx: RequestContext[DeleteEventRequest, DeleteEventResponse], /) -> DeleteEventResponse:
        """
        Idempotently remove an event record. Resets a delivered signal so
        `WaitEvent` returns pending again on the next workflow invocation.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_run(self, request: DeleteRunRequest, ctx: RequestContext[DeleteRunRequest, DeleteRunResponse], /) -> DeleteRunResponse:
        """
        Recursively delete one workflow run prefix. Bounded by a single run.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def due_timers(self, request: DueTimersRequest, ctx: RequestContext[DueTimersRequest, DueTimersResponse], /) -> DueTimersResponse:
        """
        Find SCHEDULED durable timers whose `fire_at <= now` and whose parent
        workflow is still IN_PROGRESS. Operators run this on a minute cron and
        re-invoke the workflow handler for each entry, which lets a stored
        `Workflow.Sleep` resume.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class RecordStoreServiceASGIApplication(ConnectASGIApplication[RecordStoreService]):
    def __init__(
        self,
        service: RecordStoreService | AsyncGenerator[RecordStoreService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/temporaless.v1.RecordStoreService/GetStoreCapabilities": Endpoint.unary(
                    method=MethodInfo(
                        name="GetStoreCapabilities",
                        service_name="temporaless.v1.RecordStoreService",
                        input=GetStoreCapabilitiesRequest,
                        output=GetStoreCapabilitiesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_store_capabilities,
                ),
                "/temporaless.v1.RecordStoreService/GetWorkflow": Endpoint.unary(
                    method=MethodInfo(
                        name="GetWorkflow",
                        service_name="temporaless.v1.RecordStoreService",
                        input=GetWorkflowRequest,
                        output=GetWorkflowResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_workflow,
                ),
                "/temporaless.v1.RecordStoreService/PutWorkflow": Endpoint.unary(
                    method=MethodInfo(
                        name="PutWorkflow",
                        service_name="temporaless.v1.RecordStoreService",
                        input=PutWorkflowRequest,
                        output=PutWorkflowResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.put_workflow,
                ),
                "/temporaless.v1.RecordStoreService/GetLatestWorkflowRun": Endpoint.unary(
                    method=MethodInfo(
                        name="GetLatestWorkflowRun",
                        service_name="temporaless.v1.RecordStoreService",
                        input=GetLatestWorkflowRunRequest,
                        output=GetLatestWorkflowRunResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_latest_workflow_run,
                ),
                "/temporaless.v1.RecordStoreService/GetTimer": Endpoint.unary(
                    method=MethodInfo(
                        name="GetTimer",
                        service_name="temporaless.v1.RecordStoreService",
                        input=GetTimerRequest,
                        output=GetTimerResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_timer,
                ),
                "/temporaless.v1.RecordStoreService/PutTimer": Endpoint.unary(
                    method=MethodInfo(
                        name="PutTimer",
                        service_name="temporaless.v1.RecordStoreService",
                        input=PutTimerRequest,
                        output=PutTimerResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.put_timer,
                ),
                "/temporaless.v1.RecordStoreService/GetActivity": Endpoint.unary(
                    method=MethodInfo(
                        name="GetActivity",
                        service_name="temporaless.v1.RecordStoreService",
                        input=GetActivityRequest,
                        output=GetActivityResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_activity,
                ),
                "/temporaless.v1.RecordStoreService/PutActivity": Endpoint.unary(
                    method=MethodInfo(
                        name="PutActivity",
                        service_name="temporaless.v1.RecordStoreService",
                        input=PutActivityRequest,
                        output=PutActivityResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.put_activity,
                ),
                "/temporaless.v1.RecordStoreService/GetClaim": Endpoint.unary(
                    method=MethodInfo(
                        name="GetClaim",
                        service_name="temporaless.v1.RecordStoreService",
                        input=GetClaimRequest,
                        output=GetClaimResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_claim,
                ),
                "/temporaless.v1.RecordStoreService/TryCreateClaim": Endpoint.unary(
                    method=MethodInfo(
                        name="TryCreateClaim",
                        service_name="temporaless.v1.RecordStoreService",
                        input=TryCreateClaimRequest,
                        output=TryCreateClaimResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.try_create_claim,
                ),
                "/temporaless.v1.RecordStoreService/DeleteClaim": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteClaim",
                        service_name="temporaless.v1.RecordStoreService",
                        input=DeleteClaimRequest,
                        output=DeleteClaimResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_claim,
                ),
                "/temporaless.v1.RecordStoreService/GetEvent": Endpoint.unary(
                    method=MethodInfo(
                        name="GetEvent",
                        service_name="temporaless.v1.RecordStoreService",
                        input=GetEventRequest,
                        output=GetEventResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_event,
                ),
                "/temporaless.v1.RecordStoreService/PutEvent": Endpoint.unary(
                    method=MethodInfo(
                        name="PutEvent",
                        service_name="temporaless.v1.RecordStoreService",
                        input=PutEventRequest,
                        output=PutEventResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.put_event,
                ),
                "/temporaless.v1.RecordStoreService/DeliverEvent": Endpoint.unary(
                    method=MethodInfo(
                        name="DeliverEvent",
                        service_name="temporaless.v1.RecordStoreService",
                        input=DeliverEventRequest,
                        output=DeliverEventResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.deliver_event,
                ),
                "/temporaless.v1.RecordStoreService/ListActivities": Endpoint.unary(
                    method=MethodInfo(
                        name="ListActivities",
                        service_name="temporaless.v1.RecordStoreService",
                        input=ListActivitiesRequest,
                        output=ListActivitiesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_activities,
                ),
                "/temporaless.v1.RecordStoreService/ListTimers": Endpoint.unary(
                    method=MethodInfo(
                        name="ListTimers",
                        service_name="temporaless.v1.RecordStoreService",
                        input=ListTimersRequest,
                        output=ListTimersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_timers,
                ),
                "/temporaless.v1.RecordStoreService/ListEvents": Endpoint.unary(
                    method=MethodInfo(
                        name="ListEvents",
                        service_name="temporaless.v1.RecordStoreService",
                        input=ListEventsRequest,
                        output=ListEventsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_events,
                ),
                "/temporaless.v1.RecordStoreService/ListClaims": Endpoint.unary(
                    method=MethodInfo(
                        name="ListClaims",
                        service_name="temporaless.v1.RecordStoreService",
                        input=ListClaimsRequest,
                        output=ListClaimsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_claims,
                ),
                "/temporaless.v1.RecordStoreService/DeleteWorkflow": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteWorkflow",
                        service_name="temporaless.v1.RecordStoreService",
                        input=DeleteWorkflowRequest,
                        output=DeleteWorkflowResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_workflow,
                ),
                "/temporaless.v1.RecordStoreService/DeleteActivity": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteActivity",
                        service_name="temporaless.v1.RecordStoreService",
                        input=DeleteActivityRequest,
                        output=DeleteActivityResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_activity,
                ),
                "/temporaless.v1.RecordStoreService/DeleteTimer": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteTimer",
                        service_name="temporaless.v1.RecordStoreService",
                        input=DeleteTimerRequest,
                        output=DeleteTimerResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_timer,
                ),
                "/temporaless.v1.RecordStoreService/DeleteEvent": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteEvent",
                        service_name="temporaless.v1.RecordStoreService",
                        input=DeleteEventRequest,
                        output=DeleteEventResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_event,
                ),
                "/temporaless.v1.RecordStoreService/DeleteRun": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteRun",
                        service_name="temporaless.v1.RecordStoreService",
                        input=DeleteRunRequest,
                        output=DeleteRunResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_run,
                ),
                "/temporaless.v1.RecordStoreService/DueTimers": Endpoint.unary(
                    method=MethodInfo(
                        name="DueTimers",
                        service_name="temporaless.v1.RecordStoreService",
                        input=DueTimersRequest,
                        output=DueTimersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.due_timers,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/temporaless.v1.RecordStoreService"


class RecordStoreServiceClient(ConnectClient):
    """
    RecordStoreService is the cross-language core durability contract.

    Every record kind (workflow, activity, timer, event, claim) supports
    point Get/Put/Delete. Activity, timer, event, and claim lists are scoped to
    a single workflow run for replay prefetch and run deletion. Cross-run search
    lives on RecordQueryService.

    Bucket/file backends implement this surface directly without SQL.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def get_store_capabilities(
        self,
        request: GetStoreCapabilitiesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetStoreCapabilitiesResponse:
        """
        Report what the configured store can do (claim coordination tier, etc.).
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetStoreCapabilities",
                service_name="temporaless.v1.RecordStoreService",
                input=GetStoreCapabilitiesRequest,
                output=GetStoreCapabilitiesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_workflow(
        self,
        request: GetWorkflowRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetWorkflowResponse:
        """
        Read a single workflow record by key.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetWorkflow",
                service_name="temporaless.v1.RecordStoreService",
                input=GetWorkflowRequest,
                output=GetWorkflowResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def put_workflow(
        self,
        request: PutWorkflowRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> PutWorkflowResponse:
        """
        Write or replace a single workflow record.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PutWorkflow",
                service_name="temporaless.v1.RecordStoreService",
                input=PutWorkflowRequest,
                output=PutWorkflowResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_latest_workflow_run(
        self,
        request: GetLatestWorkflowRunRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetLatestWorkflowRunResponse:
        """
        Read the derived latest-run pointer for one workflow_id.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetLatestWorkflowRun",
                service_name="temporaless.v1.RecordStoreService",
                input=GetLatestWorkflowRunRequest,
                output=GetLatestWorkflowRunResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_timer(
        self,
        request: GetTimerRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetTimerResponse:
        """
        Read a single durable timer record by key.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetTimer",
                service_name="temporaless.v1.RecordStoreService",
                input=GetTimerRequest,
                output=GetTimerResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def put_timer(
        self,
        request: PutTimerRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> PutTimerResponse:
        """
        Write or replace a single timer record.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PutTimer",
                service_name="temporaless.v1.RecordStoreService",
                input=PutTimerRequest,
                output=PutTimerResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_activity(
        self,
        request: GetActivityRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetActivityResponse:
        """
        Read a single activity record by key.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetActivity",
                service_name="temporaless.v1.RecordStoreService",
                input=GetActivityRequest,
                output=GetActivityResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def put_activity(
        self,
        request: PutActivityRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> PutActivityResponse:
        """
        Write or replace a single activity record.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PutActivity",
                service_name="temporaless.v1.RecordStoreService",
                input=PutActivityRequest,
                output=PutActivityResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_claim(
        self,
        request: GetClaimRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetClaimResponse:
        """
        Read a single coordination claim by key.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetClaim",
                service_name="temporaless.v1.RecordStoreService",
                input=GetClaimRequest,
                output=GetClaimResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def try_create_claim(
        self,
        request: TryCreateClaimRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> TryCreateClaimResponse:
        """
        Write a claim only if none already exists at the key. Returns
        `created=false` when the key is taken. Core workflow, activity, and
        concurrency coordination treats every existing claim as busy, including
        one with the same owner_id.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="TryCreateClaim",
                service_name="temporaless.v1.RecordStoreService",
                input=TryCreateClaimRequest,
                output=TryCreateClaimResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_claim(
        self,
        request: DeleteClaimRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> DeleteClaimResponse:
        """
        Idempotently release a claim. Used for workflow-execution, activity, and
        concurrency claims at durable/orderly boundaries; safe when the key is
        absent.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteClaim",
                service_name="temporaless.v1.RecordStoreService",
                input=DeleteClaimRequest,
                output=DeleteClaimResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_event(
        self,
        request: GetEventRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetEventResponse:
        """
        Read a single signal/event record by key.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetEvent",
                service_name="temporaless.v1.RecordStoreService",
                input=GetEventRequest,
                output=GetEventResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def put_event(
        self,
        request: PutEventRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> PutEventResponse:
        """
        Deliver a signal payload to a waiting workflow. External services
        that intentionally need replace semantics may call this low-level point
        write. Prefer DeliverEvent for create-once external delivery.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PutEvent",
                service_name="temporaless.v1.RecordStoreService",
                input=PutEventRequest,
                output=PutEventResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def deliver_event(
        self,
        request: DeliverEventRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> DeliverEventResponse:
        """
        Atomically establish the first payload for an EventKey. An identical
        duplicate is idempotent; a different payload fails with
        FAILED_PRECONDITION. Backends without conditional creation reject the
        operation rather than emulating it with check-then-write.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeliverEvent",
                service_name="temporaless.v1.RecordStoreService",
                input=DeliverEventRequest,
                output=DeliverEventResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_activities(
        self,
        request: ListActivitiesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListActivitiesResponse:
        """
        List all activity records under a single workflow run.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListActivities",
                service_name="temporaless.v1.RecordStoreService",
                input=ListActivitiesRequest,
                output=ListActivitiesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_timers(
        self,
        request: ListTimersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListTimersResponse:
        """
        List timer records under a single workflow run, optionally filtered by status.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListTimers",
                service_name="temporaless.v1.RecordStoreService",
                input=ListTimersRequest,
                output=ListTimersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_events(
        self,
        request: ListEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListEventsResponse:
        """
        List event records under a single workflow run.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListEvents",
                service_name="temporaless.v1.RecordStoreService",
                input=ListEventsRequest,
                output=ListEventsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_claims(
        self,
        request: ListClaimsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListClaimsResponse:
        """
        List coordination claims under a single workflow run. This is the narrow
        run-deletion seam, not a cross-run query API.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListClaims",
                service_name="temporaless.v1.RecordStoreService",
                input=ListClaimsRequest,
                output=ListClaimsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_workflow(
        self,
        request: DeleteWorkflowRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> DeleteWorkflowResponse:
        """
        Idempotently remove a workflow record only.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteWorkflow",
                service_name="temporaless.v1.RecordStoreService",
                input=DeleteWorkflowRequest,
                output=DeleteWorkflowResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_activity(
        self,
        request: DeleteActivityRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> DeleteActivityResponse:
        """
        Idempotently remove an activity record so the next `ExecuteActivity`
        re-executes the activity body.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteActivity",
                service_name="temporaless.v1.RecordStoreService",
                input=DeleteActivityRequest,
                output=DeleteActivityResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_timer(
        self,
        request: DeleteTimerRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> DeleteTimerResponse:
        """
        Idempotently remove a timer record.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteTimer",
                service_name="temporaless.v1.RecordStoreService",
                input=DeleteTimerRequest,
                output=DeleteTimerResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_event(
        self,
        request: DeleteEventRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> DeleteEventResponse:
        """
        Idempotently remove an event record. Resets a delivered signal so
        `WaitEvent` returns pending again on the next workflow invocation.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteEvent",
                service_name="temporaless.v1.RecordStoreService",
                input=DeleteEventRequest,
                output=DeleteEventResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_run(
        self,
        request: DeleteRunRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> DeleteRunResponse:
        """
        Recursively delete one workflow run prefix. Bounded by a single run.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteRun",
                service_name="temporaless.v1.RecordStoreService",
                input=DeleteRunRequest,
                output=DeleteRunResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def due_timers(
        self,
        request: DueTimersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> DueTimersResponse:
        """
        Find SCHEDULED durable timers whose `fire_at <= now` and whose parent
        workflow is still IN_PROGRESS. Operators run this on a minute cron and
        re-invoke the workflow handler for each entry, which lets a stored
        `Workflow.Sleep` resume.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DueTimers",
                service_name="temporaless.v1.RecordStoreService",
                input=DueTimersRequest,
                output=DueTimersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class RecordQueryService(Protocol):
    """
    RecordQueryService is the optional cross-run search and retention surface.
    Implementations are derived indexes that store record keys and metadata only;
    the Python adapter is SQLite today. The bucket remains the source of truth.
    """
    async def list_workflows(self, request: ListWorkflowsRequest, ctx: RequestContext[ListWorkflowsRequest, ListWorkflowsResponse], /) -> ListWorkflowsResponse:
        """
        List workflow records with server-side filters, ordering, and pagination.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_activities(self, request: RecordQueryServiceListActivitiesRequest, ctx: RequestContext[RecordQueryServiceListActivitiesRequest, RecordQueryServiceListActivitiesResponse], /) -> RecordQueryServiceListActivitiesResponse:
        """
        List activity records across runs or under one run, depending on filters.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def sweep(self, request: SweepRequest, ctx: RequestContext[SweepRequest, SweepResponse], /) -> SweepResponse:
        """
        Indexed retention sweep. The implementation prevalidates claim and record
        snapshots, removes run-scoped claims before bucket records, and then
        removes index rows. Eligible runs must be externally quiesced; this RPC is
        not a transaction or execution fence.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def due_timers(self, request: RecordQueryServiceDueTimersRequest, ctx: RequestContext[RecordQueryServiceDueTimersRequest, RecordQueryServiceDueTimersResponse], /) -> RecordQueryServiceDueTimersResponse:
        """
        Optional indexed due-timer scan. Bucket-only deployments use the
        RecordStoreService ledger implementation.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class RecordQueryServiceASGIApplication(ConnectASGIApplication[RecordQueryService]):
    def __init__(
        self,
        service: RecordQueryService | AsyncGenerator[RecordQueryService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/temporaless.v1.RecordQueryService/ListWorkflows": Endpoint.unary(
                    method=MethodInfo(
                        name="ListWorkflows",
                        service_name="temporaless.v1.RecordQueryService",
                        input=ListWorkflowsRequest,
                        output=ListWorkflowsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_workflows,
                ),
                "/temporaless.v1.RecordQueryService/ListActivities": Endpoint.unary(
                    method=MethodInfo(
                        name="ListActivities",
                        service_name="temporaless.v1.RecordQueryService",
                        input=RecordQueryServiceListActivitiesRequest,
                        output=RecordQueryServiceListActivitiesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_activities,
                ),
                "/temporaless.v1.RecordQueryService/Sweep": Endpoint.unary(
                    method=MethodInfo(
                        name="Sweep",
                        service_name="temporaless.v1.RecordQueryService",
                        input=SweepRequest,
                        output=SweepResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.sweep,
                ),
                "/temporaless.v1.RecordQueryService/DueTimers": Endpoint.unary(
                    method=MethodInfo(
                        name="DueTimers",
                        service_name="temporaless.v1.RecordQueryService",
                        input=RecordQueryServiceDueTimersRequest,
                        output=RecordQueryServiceDueTimersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.due_timers,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/temporaless.v1.RecordQueryService"


class RecordQueryServiceClient(ConnectClient):
    """
    RecordQueryService is the optional cross-run search and retention surface.
    Implementations are derived indexes that store record keys and metadata only;
    the Python adapter is SQLite today. The bucket remains the source of truth.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def list_workflows(
        self,
        request: ListWorkflowsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListWorkflowsResponse:
        """
        List workflow records with server-side filters, ordering, and pagination.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListWorkflows",
                service_name="temporaless.v1.RecordQueryService",
                input=ListWorkflowsRequest,
                output=ListWorkflowsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_activities(
        self,
        request: RecordQueryServiceListActivitiesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> RecordQueryServiceListActivitiesResponse:
        """
        List activity records across runs or under one run, depending on filters.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListActivities",
                service_name="temporaless.v1.RecordQueryService",
                input=RecordQueryServiceListActivitiesRequest,
                output=RecordQueryServiceListActivitiesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def sweep(
        self,
        request: SweepRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> SweepResponse:
        """
        Indexed retention sweep. The implementation prevalidates claim and record
        snapshots, removes run-scoped claims before bucket records, and then
        removes index rows. Eligible runs must be externally quiesced; this RPC is
        not a transaction or execution fence.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Sweep",
                service_name="temporaless.v1.RecordQueryService",
                input=SweepRequest,
                output=SweepResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def due_timers(
        self,
        request: RecordQueryServiceDueTimersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> RecordQueryServiceDueTimersResponse:
        """
        Optional indexed due-timer scan. Bucket-only deployments use the
        RecordStoreService ledger implementation.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DueTimers",
                service_name="temporaless.v1.RecordQueryService",
                input=RecordQueryServiceDueTimersRequest,
                output=RecordQueryServiceDueTimersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
