# Generated from temporaless/v1/temporaless.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.1 with parameter "protobuf=google,io=async".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, Endpoint
from pyqwest import Client

from .temporaless_pb2 import DeleteActivityRequest, DeleteActivityResponse, DeleteClaimRequest, DeleteClaimResponse, DeleteEventRequest, DeleteEventResponse, DeleteRunRequest, DeleteRunResponse, DeleteTimerRequest, DeleteTimerResponse, DeleteWorkflowRequest, DeleteWorkflowResponse, DueTimersRequest, DueTimersResponse, GetActivityRequest, GetActivityResponse, GetClaimRequest, GetClaimResponse, GetEventRequest, GetEventResponse, GetLatestWorkflowRunRequest, GetLatestWorkflowRunResponse, GetStoreCapabilitiesRequest, GetStoreCapabilitiesResponse, GetTimerRequest, GetTimerResponse, GetWorkflowRequest, GetWorkflowResponse, ListActivitiesRequest, ListActivitiesResponse, ListClaimsRequest, ListClaimsResponse, ListEventsRequest, ListEventsResponse, ListTimersRequest, ListTimersResponse, ListWorkflowsRequest, ListWorkflowsResponse, PutActivityRequest, PutActivityResponse, PutEventRequest, PutEventResponse, PutTimerRequest, PutTimerResponse, PutWorkflowRequest, PutWorkflowResponse, RecordQueryServiceDueTimersRequest, RecordQueryServiceDueTimersResponse, RecordQueryServiceListActivitiesRequest, RecordQueryServiceListActivitiesResponse, SweepRequest, SweepResponse, TryCreateClaimRequest, TryCreateClaimResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class RecordStoreService(Protocol):
    async def get_store_capabilities(self, request: GetStoreCapabilitiesRequest, ctx: RequestContext[GetStoreCapabilitiesRequest, GetStoreCapabilitiesResponse]) -> GetStoreCapabilitiesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_workflow(self, request: GetWorkflowRequest, ctx: RequestContext[GetWorkflowRequest, GetWorkflowResponse]) -> GetWorkflowResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def put_workflow(self, request: PutWorkflowRequest, ctx: RequestContext[PutWorkflowRequest, PutWorkflowResponse]) -> PutWorkflowResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_latest_workflow_run(self, request: GetLatestWorkflowRunRequest, ctx: RequestContext[GetLatestWorkflowRunRequest, GetLatestWorkflowRunResponse]) -> GetLatestWorkflowRunResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_timer(self, request: GetTimerRequest, ctx: RequestContext[GetTimerRequest, GetTimerResponse]) -> GetTimerResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def put_timer(self, request: PutTimerRequest, ctx: RequestContext[PutTimerRequest, PutTimerResponse]) -> PutTimerResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_activity(self, request: GetActivityRequest, ctx: RequestContext[GetActivityRequest, GetActivityResponse]) -> GetActivityResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def put_activity(self, request: PutActivityRequest, ctx: RequestContext[PutActivityRequest, PutActivityResponse]) -> PutActivityResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_claim(self, request: GetClaimRequest, ctx: RequestContext[GetClaimRequest, GetClaimResponse]) -> GetClaimResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def try_create_claim(self, request: TryCreateClaimRequest, ctx: RequestContext[TryCreateClaimRequest, TryCreateClaimResponse]) -> TryCreateClaimResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_claim(self, request: DeleteClaimRequest, ctx: RequestContext[DeleteClaimRequest, DeleteClaimResponse]) -> DeleteClaimResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_event(self, request: GetEventRequest, ctx: RequestContext[GetEventRequest, GetEventResponse]) -> GetEventResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def put_event(self, request: PutEventRequest, ctx: RequestContext[PutEventRequest, PutEventResponse]) -> PutEventResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_activities(self, request: ListActivitiesRequest, ctx: RequestContext[ListActivitiesRequest, ListActivitiesResponse]) -> ListActivitiesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_timers(self, request: ListTimersRequest, ctx: RequestContext[ListTimersRequest, ListTimersResponse]) -> ListTimersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_events(self, request: ListEventsRequest, ctx: RequestContext[ListEventsRequest, ListEventsResponse]) -> ListEventsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_claims(self, request: ListClaimsRequest, ctx: RequestContext[ListClaimsRequest, ListClaimsResponse]) -> ListClaimsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_workflow(self, request: DeleteWorkflowRequest, ctx: RequestContext[DeleteWorkflowRequest, DeleteWorkflowResponse]) -> DeleteWorkflowResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_activity(self, request: DeleteActivityRequest, ctx: RequestContext[DeleteActivityRequest, DeleteActivityResponse]) -> DeleteActivityResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_timer(self, request: DeleteTimerRequest, ctx: RequestContext[DeleteTimerRequest, DeleteTimerResponse]) -> DeleteTimerResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_event(self, request: DeleteEventRequest, ctx: RequestContext[DeleteEventRequest, DeleteEventResponse]) -> DeleteEventResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_run(self, request: DeleteRunRequest, ctx: RequestContext[DeleteRunRequest, DeleteRunResponse]) -> DeleteRunResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def due_timers(self, request: DueTimersRequest, ctx: RequestContext[DueTimersRequest, DueTimersResponse]) -> DueTimersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class RecordStoreServiceASGIApplication(ConnectASGIApplication[RecordStoreService]):
    def __init__(
        self,
        service: RecordStoreService | AsyncGenerator[RecordStoreService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/temporaless.v1.RecordStoreService/GetStoreCapabilities": Endpoint.unary(
                    method=MethodInfo(
                        name="GetStoreCapabilities",
                        service_name="temporaless.v1.RecordStoreService",
                        input=GetStoreCapabilitiesRequest,
                        output=GetStoreCapabilitiesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_store_capabilities,
                ),
                "/temporaless.v1.RecordStoreService/GetWorkflow": Endpoint.unary(
                    method=MethodInfo(
                        name="GetWorkflow",
                        service_name="temporaless.v1.RecordStoreService",
                        input=GetWorkflowRequest,
                        output=GetWorkflowResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_workflow,
                ),
                "/temporaless.v1.RecordStoreService/PutWorkflow": Endpoint.unary(
                    method=MethodInfo(
                        name="PutWorkflow",
                        service_name="temporaless.v1.RecordStoreService",
                        input=PutWorkflowRequest,
                        output=PutWorkflowResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.put_workflow,
                ),
                "/temporaless.v1.RecordStoreService/GetLatestWorkflowRun": Endpoint.unary(
                    method=MethodInfo(
                        name="GetLatestWorkflowRun",
                        service_name="temporaless.v1.RecordStoreService",
                        input=GetLatestWorkflowRunRequest,
                        output=GetLatestWorkflowRunResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_latest_workflow_run,
                ),
                "/temporaless.v1.RecordStoreService/GetTimer": Endpoint.unary(
                    method=MethodInfo(
                        name="GetTimer",
                        service_name="temporaless.v1.RecordStoreService",
                        input=GetTimerRequest,
                        output=GetTimerResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_timer,
                ),
                "/temporaless.v1.RecordStoreService/PutTimer": Endpoint.unary(
                    method=MethodInfo(
                        name="PutTimer",
                        service_name="temporaless.v1.RecordStoreService",
                        input=PutTimerRequest,
                        output=PutTimerResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.put_timer,
                ),
                "/temporaless.v1.RecordStoreService/GetActivity": Endpoint.unary(
                    method=MethodInfo(
                        name="GetActivity",
                        service_name="temporaless.v1.RecordStoreService",
                        input=GetActivityRequest,
                        output=GetActivityResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_activity,
                ),
                "/temporaless.v1.RecordStoreService/PutActivity": Endpoint.unary(
                    method=MethodInfo(
                        name="PutActivity",
                        service_name="temporaless.v1.RecordStoreService",
                        input=PutActivityRequest,
                        output=PutActivityResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.put_activity,
                ),
                "/temporaless.v1.RecordStoreService/GetClaim": Endpoint.unary(
                    method=MethodInfo(
                        name="GetClaim",
                        service_name="temporaless.v1.RecordStoreService",
                        input=GetClaimRequest,
                        output=GetClaimResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_claim,
                ),
                "/temporaless.v1.RecordStoreService/TryCreateClaim": Endpoint.unary(
                    method=MethodInfo(
                        name="TryCreateClaim",
                        service_name="temporaless.v1.RecordStoreService",
                        input=TryCreateClaimRequest,
                        output=TryCreateClaimResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.try_create_claim,
                ),
                "/temporaless.v1.RecordStoreService/DeleteClaim": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteClaim",
                        service_name="temporaless.v1.RecordStoreService",
                        input=DeleteClaimRequest,
                        output=DeleteClaimResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_claim,
                ),
                "/temporaless.v1.RecordStoreService/GetEvent": Endpoint.unary(
                    method=MethodInfo(
                        name="GetEvent",
                        service_name="temporaless.v1.RecordStoreService",
                        input=GetEventRequest,
                        output=GetEventResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_event,
                ),
                "/temporaless.v1.RecordStoreService/PutEvent": Endpoint.unary(
                    method=MethodInfo(
                        name="PutEvent",
                        service_name="temporaless.v1.RecordStoreService",
                        input=PutEventRequest,
                        output=PutEventResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.put_event,
                ),
                "/temporaless.v1.RecordStoreService/ListActivities": Endpoint.unary(
                    method=MethodInfo(
                        name="ListActivities",
                        service_name="temporaless.v1.RecordStoreService",
                        input=ListActivitiesRequest,
                        output=ListActivitiesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_activities,
                ),
                "/temporaless.v1.RecordStoreService/ListTimers": Endpoint.unary(
                    method=MethodInfo(
                        name="ListTimers",
                        service_name="temporaless.v1.RecordStoreService",
                        input=ListTimersRequest,
                        output=ListTimersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_timers,
                ),
                "/temporaless.v1.RecordStoreService/ListEvents": Endpoint.unary(
                    method=MethodInfo(
                        name="ListEvents",
                        service_name="temporaless.v1.RecordStoreService",
                        input=ListEventsRequest,
                        output=ListEventsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_events,
                ),
                "/temporaless.v1.RecordStoreService/ListClaims": Endpoint.unary(
                    method=MethodInfo(
                        name="ListClaims",
                        service_name="temporaless.v1.RecordStoreService",
                        input=ListClaimsRequest,
                        output=ListClaimsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_claims,
                ),
                "/temporaless.v1.RecordStoreService/DeleteWorkflow": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteWorkflow",
                        service_name="temporaless.v1.RecordStoreService",
                        input=DeleteWorkflowRequest,
                        output=DeleteWorkflowResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_workflow,
                ),
                "/temporaless.v1.RecordStoreService/DeleteActivity": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteActivity",
                        service_name="temporaless.v1.RecordStoreService",
                        input=DeleteActivityRequest,
                        output=DeleteActivityResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_activity,
                ),
                "/temporaless.v1.RecordStoreService/DeleteTimer": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteTimer",
                        service_name="temporaless.v1.RecordStoreService",
                        input=DeleteTimerRequest,
                        output=DeleteTimerResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_timer,
                ),
                "/temporaless.v1.RecordStoreService/DeleteEvent": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteEvent",
                        service_name="temporaless.v1.RecordStoreService",
                        input=DeleteEventRequest,
                        output=DeleteEventResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_event,
                ),
                "/temporaless.v1.RecordStoreService/DeleteRun": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteRun",
                        service_name="temporaless.v1.RecordStoreService",
                        input=DeleteRunRequest,
                        output=DeleteRunResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_run,
                ),
                "/temporaless.v1.RecordStoreService/DueTimers": Endpoint.unary(
                    method=MethodInfo(
                        name="DueTimers",
                        service_name="temporaless.v1.RecordStoreService",
                        input=DueTimersRequest,
                        output=DueTimersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.due_timers,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/temporaless.v1.RecordStoreService"


class RecordStoreServiceClient(ConnectClient):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def get_store_capabilities(
        self,
        request: GetStoreCapabilitiesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetStoreCapabilitiesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetStoreCapabilities",
                service_name="temporaless.v1.RecordStoreService",
                input=GetStoreCapabilitiesRequest,
                output=GetStoreCapabilitiesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_workflow(
        self,
        request: GetWorkflowRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetWorkflowResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetWorkflow",
                service_name="temporaless.v1.RecordStoreService",
                input=GetWorkflowRequest,
                output=GetWorkflowResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def put_workflow(
        self,
        request: PutWorkflowRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> PutWorkflowResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PutWorkflow",
                service_name="temporaless.v1.RecordStoreService",
                input=PutWorkflowRequest,
                output=PutWorkflowResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_latest_workflow_run(
        self,
        request: GetLatestWorkflowRunRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetLatestWorkflowRunResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetLatestWorkflowRun",
                service_name="temporaless.v1.RecordStoreService",
                input=GetLatestWorkflowRunRequest,
                output=GetLatestWorkflowRunResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_timer(
        self,
        request: GetTimerRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetTimerResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetTimer",
                service_name="temporaless.v1.RecordStoreService",
                input=GetTimerRequest,
                output=GetTimerResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def put_timer(
        self,
        request: PutTimerRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> PutTimerResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PutTimer",
                service_name="temporaless.v1.RecordStoreService",
                input=PutTimerRequest,
                output=PutTimerResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_activity(
        self,
        request: GetActivityRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetActivityResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetActivity",
                service_name="temporaless.v1.RecordStoreService",
                input=GetActivityRequest,
                output=GetActivityResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def put_activity(
        self,
        request: PutActivityRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> PutActivityResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PutActivity",
                service_name="temporaless.v1.RecordStoreService",
                input=PutActivityRequest,
                output=PutActivityResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_claim(
        self,
        request: GetClaimRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetClaimResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetClaim",
                service_name="temporaless.v1.RecordStoreService",
                input=GetClaimRequest,
                output=GetClaimResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def try_create_claim(
        self,
        request: TryCreateClaimRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> TryCreateClaimResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="TryCreateClaim",
                service_name="temporaless.v1.RecordStoreService",
                input=TryCreateClaimRequest,
                output=TryCreateClaimResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_claim(
        self,
        request: DeleteClaimRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> DeleteClaimResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteClaim",
                service_name="temporaless.v1.RecordStoreService",
                input=DeleteClaimRequest,
                output=DeleteClaimResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_event(
        self,
        request: GetEventRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetEventResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetEvent",
                service_name="temporaless.v1.RecordStoreService",
                input=GetEventRequest,
                output=GetEventResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def put_event(
        self,
        request: PutEventRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> PutEventResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PutEvent",
                service_name="temporaless.v1.RecordStoreService",
                input=PutEventRequest,
                output=PutEventResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_activities(
        self,
        request: ListActivitiesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListActivitiesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListActivities",
                service_name="temporaless.v1.RecordStoreService",
                input=ListActivitiesRequest,
                output=ListActivitiesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_timers(
        self,
        request: ListTimersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListTimersResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListTimers",
                service_name="temporaless.v1.RecordStoreService",
                input=ListTimersRequest,
                output=ListTimersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_events(
        self,
        request: ListEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListEventsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListEvents",
                service_name="temporaless.v1.RecordStoreService",
                input=ListEventsRequest,
                output=ListEventsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_claims(
        self,
        request: ListClaimsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListClaimsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListClaims",
                service_name="temporaless.v1.RecordStoreService",
                input=ListClaimsRequest,
                output=ListClaimsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_workflow(
        self,
        request: DeleteWorkflowRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> DeleteWorkflowResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteWorkflow",
                service_name="temporaless.v1.RecordStoreService",
                input=DeleteWorkflowRequest,
                output=DeleteWorkflowResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_activity(
        self,
        request: DeleteActivityRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> DeleteActivityResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteActivity",
                service_name="temporaless.v1.RecordStoreService",
                input=DeleteActivityRequest,
                output=DeleteActivityResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_timer(
        self,
        request: DeleteTimerRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> DeleteTimerResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteTimer",
                service_name="temporaless.v1.RecordStoreService",
                input=DeleteTimerRequest,
                output=DeleteTimerResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_event(
        self,
        request: DeleteEventRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> DeleteEventResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteEvent",
                service_name="temporaless.v1.RecordStoreService",
                input=DeleteEventRequest,
                output=DeleteEventResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_run(
        self,
        request: DeleteRunRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> DeleteRunResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteRun",
                service_name="temporaless.v1.RecordStoreService",
                input=DeleteRunRequest,
                output=DeleteRunResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def due_timers(
        self,
        request: DueTimersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> DueTimersResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DueTimers",
                service_name="temporaless.v1.RecordStoreService",
                input=DueTimersRequest,
                output=DueTimersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class RecordQueryService(Protocol):
    async def list_workflows(self, request: ListWorkflowsRequest, ctx: RequestContext[ListWorkflowsRequest, ListWorkflowsResponse]) -> ListWorkflowsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_activities(self, request: RecordQueryServiceListActivitiesRequest, ctx: RequestContext[RecordQueryServiceListActivitiesRequest, RecordQueryServiceListActivitiesResponse]) -> RecordQueryServiceListActivitiesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def sweep(self, request: SweepRequest, ctx: RequestContext[SweepRequest, SweepResponse]) -> SweepResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def due_timers(self, request: RecordQueryServiceDueTimersRequest, ctx: RequestContext[RecordQueryServiceDueTimersRequest, RecordQueryServiceDueTimersResponse]) -> RecordQueryServiceDueTimersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class RecordQueryServiceASGIApplication(ConnectASGIApplication[RecordQueryService]):
    def __init__(
        self,
        service: RecordQueryService | AsyncGenerator[RecordQueryService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/temporaless.v1.RecordQueryService/ListWorkflows": Endpoint.unary(
                    method=MethodInfo(
                        name="ListWorkflows",
                        service_name="temporaless.v1.RecordQueryService",
                        input=ListWorkflowsRequest,
                        output=ListWorkflowsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_workflows,
                ),
                "/temporaless.v1.RecordQueryService/ListActivities": Endpoint.unary(
                    method=MethodInfo(
                        name="ListActivities",
                        service_name="temporaless.v1.RecordQueryService",
                        input=RecordQueryServiceListActivitiesRequest,
                        output=RecordQueryServiceListActivitiesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_activities,
                ),
                "/temporaless.v1.RecordQueryService/Sweep": Endpoint.unary(
                    method=MethodInfo(
                        name="Sweep",
                        service_name="temporaless.v1.RecordQueryService",
                        input=SweepRequest,
                        output=SweepResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.sweep,
                ),
                "/temporaless.v1.RecordQueryService/DueTimers": Endpoint.unary(
                    method=MethodInfo(
                        name="DueTimers",
                        service_name="temporaless.v1.RecordQueryService",
                        input=RecordQueryServiceDueTimersRequest,
                        output=RecordQueryServiceDueTimersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.due_timers,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/temporaless.v1.RecordQueryService"


class RecordQueryServiceClient(ConnectClient):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def list_workflows(
        self,
        request: ListWorkflowsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListWorkflowsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListWorkflows",
                service_name="temporaless.v1.RecordQueryService",
                input=ListWorkflowsRequest,
                output=ListWorkflowsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_activities(
        self,
        request: RecordQueryServiceListActivitiesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> RecordQueryServiceListActivitiesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListActivities",
                service_name="temporaless.v1.RecordQueryService",
                input=RecordQueryServiceListActivitiesRequest,
                output=RecordQueryServiceListActivitiesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def sweep(
        self,
        request: SweepRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> SweepResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Sweep",
                service_name="temporaless.v1.RecordQueryService",
                input=SweepRequest,
                output=SweepResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def due_timers(
        self,
        request: RecordQueryServiceDueTimersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> RecordQueryServiceDueTimersResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DueTimers",
                service_name="temporaless.v1.RecordQueryService",
                input=RecordQueryServiceDueTimersRequest,
                output=RecordQueryServiceDueTimersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
