// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: medallion/terminal/v1/terminal.proto

package terminalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TerminalService_Get_FullMethodName          = "/medallion.terminal.v1.TerminalService/Get"
	TerminalService_Stream_FullMethodName       = "/medallion.terminal.v1.TerminalService/Stream"
	TerminalService_ListSources_FullMethodName  = "/medallion.terminal.v1.TerminalService/ListSources"
	TerminalService_Generate_FullMethodName     = "/medallion.terminal.v1.TerminalService/Generate"
	TerminalService_SubmitAction_FullMethodName = "/medallion.terminal.v1.TerminalService/SubmitAction"
	TerminalService_WatchAction_FullMethodName  = "/medallion.terminal.v1.TerminalService/WatchAction"
)

// TerminalServiceClient is the client API for TerminalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TerminalService is the single RPC surface a backend implements
// to power a dashboard: read (Get / Stream), catalog (ListSources),
// AI (Generate), and write (SubmitAction / WatchAction).
type TerminalServiceClient interface {
	// One-shot fetch for a registered source.
	Get(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error)
	// Server-streaming fetch — backend pushes updated payloads.
	// Use for live data (prices, sentiment, status feeds).
	Stream(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataResponse], error)
	// Discover every source the backend can serve. The result feeds
	// both the AI prompt (so it knows what to wire up) and any
	// dashboard-authoring UI.
	ListSources(ctx context.Context, in *ListSourcesRequest, opts ...grpc.CallOption) (*ListSourcesResponse, error)
	// Convert a natural-language prompt into widget mutations or a
	// full dashboard. The frontend applies the returned actions.
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
	// Submit a write-side action. Generic dispatch for form-like widgets
	// (Trade, future swap/vote/message widgets). Backend dispatches on
	// `action_id` to a domain-specific handler. Keeps the framework
	// generic — only the dispatch envelope is in this proto; the
	// per-action parameter shape is by convention between widget and
	// backend.
	SubmitAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	// Subscribe to lifecycle updates for a previously submitted action.
	// Required when SubmitAction returned a non-terminal status
	// (ACCEPTED or PENDING) and the caller needs the eventual outcome.
	// The backend MUST send updates monotonically by `sequence` and MUST
	// close the stream after a terminal status (OK, REJECTED, FAILED,
	// CANCELLED). Identify the action by ANY of action_id/id/
	// client_request_id — at least one must be set.
	WatchAction(ctx context.Context, in *ActionWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActionUpdate], error)
}

type terminalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTerminalServiceClient(cc grpc.ClientConnInterface) TerminalServiceClient {
	return &terminalServiceClient{cc}
}

func (c *terminalServiceClient) Get(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, TerminalService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) Stream(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TerminalService_ServiceDesc.Streams[0], TerminalService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataRequest, DataResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TerminalService_StreamClient = grpc.ServerStreamingClient[DataResponse]

func (c *terminalServiceClient) ListSources(ctx context.Context, in *ListSourcesRequest, opts ...grpc.CallOption) (*ListSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSourcesResponse)
	err := c.cc.Invoke(ctx, TerminalService_ListSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateResponse)
	err := c.cc.Invoke(ctx, TerminalService_Generate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) SubmitAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, TerminalService_SubmitAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) WatchAction(ctx context.Context, in *ActionWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActionUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TerminalService_ServiceDesc.Streams[1], TerminalService_WatchAction_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ActionWatchRequest, ActionUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TerminalService_WatchActionClient = grpc.ServerStreamingClient[ActionUpdate]

// TerminalServiceServer is the server API for TerminalService service.
// All implementations must embed UnimplementedTerminalServiceServer
// for forward compatibility.
//
// TerminalService is the single RPC surface a backend implements
// to power a dashboard: read (Get / Stream), catalog (ListSources),
// AI (Generate), and write (SubmitAction / WatchAction).
type TerminalServiceServer interface {
	// One-shot fetch for a registered source.
	Get(context.Context, *DataRequest) (*DataResponse, error)
	// Server-streaming fetch — backend pushes updated payloads.
	// Use for live data (prices, sentiment, status feeds).
	Stream(*DataRequest, grpc.ServerStreamingServer[DataResponse]) error
	// Discover every source the backend can serve. The result feeds
	// both the AI prompt (so it knows what to wire up) and any
	// dashboard-authoring UI.
	ListSources(context.Context, *ListSourcesRequest) (*ListSourcesResponse, error)
	// Convert a natural-language prompt into widget mutations or a
	// full dashboard. The frontend applies the returned actions.
	Generate(context.Context, *GenerateRequest) (*GenerateResponse, error)
	// Submit a write-side action. Generic dispatch for form-like widgets
	// (Trade, future swap/vote/message widgets). Backend dispatches on
	// `action_id` to a domain-specific handler. Keeps the framework
	// generic — only the dispatch envelope is in this proto; the
	// per-action parameter shape is by convention between widget and
	// backend.
	SubmitAction(context.Context, *ActionRequest) (*ActionResponse, error)
	// Subscribe to lifecycle updates for a previously submitted action.
	// Required when SubmitAction returned a non-terminal status
	// (ACCEPTED or PENDING) and the caller needs the eventual outcome.
	// The backend MUST send updates monotonically by `sequence` and MUST
	// close the stream after a terminal status (OK, REJECTED, FAILED,
	// CANCELLED). Identify the action by ANY of action_id/id/
	// client_request_id — at least one must be set.
	WatchAction(*ActionWatchRequest, grpc.ServerStreamingServer[ActionUpdate]) error
	mustEmbedUnimplementedTerminalServiceServer()
}

// UnimplementedTerminalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTerminalServiceServer struct{}

func (UnimplementedTerminalServiceServer) Get(context.Context, *DataRequest) (*DataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTerminalServiceServer) Stream(*DataRequest, grpc.ServerStreamingServer[DataResponse]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedTerminalServiceServer) ListSources(context.Context, *ListSourcesRequest) (*ListSourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSources not implemented")
}
func (UnimplementedTerminalServiceServer) Generate(context.Context, *GenerateRequest) (*GenerateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedTerminalServiceServer) SubmitAction(context.Context, *ActionRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitAction not implemented")
}
func (UnimplementedTerminalServiceServer) WatchAction(*ActionWatchRequest, grpc.ServerStreamingServer[ActionUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchAction not implemented")
}
func (UnimplementedTerminalServiceServer) mustEmbedUnimplementedTerminalServiceServer() {}
func (UnimplementedTerminalServiceServer) testEmbeddedByValue()                         {}

// UnsafeTerminalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TerminalServiceServer will
// result in compilation errors.
type UnsafeTerminalServiceServer interface {
	mustEmbedUnimplementedTerminalServiceServer()
}

func RegisterTerminalServiceServer(s grpc.ServiceRegistrar, srv TerminalServiceServer) {
	// If the following call panics, it indicates UnimplementedTerminalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TerminalService_ServiceDesc, srv)
}

func _TerminalService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).Get(ctx, req.(*DataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TerminalServiceServer).Stream(m, &grpc.GenericServerStream[DataRequest, DataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TerminalService_StreamServer = grpc.ServerStreamingServer[DataResponse]

func _TerminalService_ListSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).ListSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_ListSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).ListSources(ctx, req.(*ListSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).Generate(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_SubmitAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).SubmitAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_SubmitAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).SubmitAction(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_WatchAction_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ActionWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TerminalServiceServer).WatchAction(m, &grpc.GenericServerStream[ActionWatchRequest, ActionUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TerminalService_WatchActionServer = grpc.ServerStreamingServer[ActionUpdate]

// TerminalService_ServiceDesc is the grpc.ServiceDesc for TerminalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TerminalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "medallion.terminal.v1.TerminalService",
	HandlerType: (*TerminalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _TerminalService_Get_Handler,
		},
		{
			MethodName: "ListSources",
			Handler:    _TerminalService_ListSources_Handler,
		},
		{
			MethodName: "Generate",
			Handler:    _TerminalService_Generate_Handler,
		},
		{
			MethodName: "SubmitAction",
			Handler:    _TerminalService_SubmitAction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _TerminalService_Stream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchAction",
			Handler:       _TerminalService_WatchAction_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "medallion/terminal/v1/terminal.proto",
}
