// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: medallion/terminal/v1/terminal.proto

package terminalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ParamType — the data type a SourceParam expects. Used by catalog
// UIs to render the right input control and by the AI to format
// substitutions correctly. Wire format is always a string in
// DataRequest.params; the backend converts based on this type.
type ParamType int32

const (
	// No type declared; treated as string.
	ParamType_PARAM_TYPE_UNSPECIFIED ParamType = 0
	// Free-form string.
	ParamType_PARAM_TYPE_STRING ParamType = 1
	// Floating-point number.
	ParamType_PARAM_TYPE_NUMBER ParamType = 2
	// "true" or "false".
	ParamType_PARAM_TYPE_BOOLEAN ParamType = 3
	// ISO 8601 timestamp with time component (e.g. "2026-04-01T00:00:00Z").
	ParamType_PARAM_TYPE_TIMESTAMP ParamType = 4
	// Duration (e.g. "1h", "7d", "30m"). Used for ranges/windows.
	ParamType_PARAM_TYPE_DURATION ParamType = 5
	// Constrained to one of `enum_values`.
	ParamType_PARAM_TYPE_ENUM ParamType = 6
	// Whole number (e.g. limit, page, depth).
	ParamType_PARAM_TYPE_INTEGER ParamType = 7
	// Date without time (e.g. "2026-04-01"). Use TIMESTAMP if the
	// time component matters.
	ParamType_PARAM_TYPE_DATE ParamType = 8
)

// Enum value maps for ParamType.
var (
	ParamType_name = map[int32]string{
		0: "PARAM_TYPE_UNSPECIFIED",
		1: "PARAM_TYPE_STRING",
		2: "PARAM_TYPE_NUMBER",
		3: "PARAM_TYPE_BOOLEAN",
		4: "PARAM_TYPE_TIMESTAMP",
		5: "PARAM_TYPE_DURATION",
		6: "PARAM_TYPE_ENUM",
		7: "PARAM_TYPE_INTEGER",
		8: "PARAM_TYPE_DATE",
	}
	ParamType_value = map[string]int32{
		"PARAM_TYPE_UNSPECIFIED": 0,
		"PARAM_TYPE_STRING":      1,
		"PARAM_TYPE_NUMBER":      2,
		"PARAM_TYPE_BOOLEAN":     3,
		"PARAM_TYPE_TIMESTAMP":   4,
		"PARAM_TYPE_DURATION":    5,
		"PARAM_TYPE_ENUM":        6,
		"PARAM_TYPE_INTEGER":     7,
		"PARAM_TYPE_DATE":        8,
	}
)

func (x ParamType) Enum() *ParamType {
	p := new(ParamType)
	*p = x
	return p
}

func (x ParamType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParamType) Descriptor() protoreflect.EnumDescriptor {
	return file_medallion_terminal_v1_terminal_proto_enumTypes[0].Descriptor()
}

func (ParamType) Type() protoreflect.EnumType {
	return &file_medallion_terminal_v1_terminal_proto_enumTypes[0]
}

func (x ParamType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParamType.Descriptor instead.
func (ParamType) EnumDescriptor() ([]byte, []int) {
	return file_medallion_terminal_v1_terminal_proto_rawDescGZIP(), []int{0}
}

// Shape names the payload variant a Source returns. The values
// mirror the cases in DataResponse.payload — a backend should set
// Source.shape to match what it actually emits.
type Shape int32

const (
	// No shape declared.
	Shape_SHAPE_UNSPECIFIED Shape = 0
	// TimeseriesPayload.
	Shape_SHAPE_TIMESERIES Shape = 1
	// CandlePayload.
	Shape_SHAPE_CANDLES Shape = 2
	// TablePayload.
	Shape_SHAPE_TABLE Shape = 3
	// MetricPayload.
	Shape_SHAPE_METRIC Shape = 4
	// GaugePayload.
	Shape_SHAPE_GAUGE Shape = 5
	// HeatmapPayload.
	Shape_SHAPE_HEATMAP Shape = 6
	// EventPayload.
	Shape_SHAPE_EVENTS Shape = 7
	// DistributionPayload.
	Shape_SHAPE_DISTRIBUTION Shape = 8
	// TextPayload.
	Shape_SHAPE_TEXT Shape = 9
	// OrderBookPayload.
	Shape_SHAPE_ORDERBOOK Shape = 10
	// PairedGridPayload.
	Shape_SHAPE_PAIRED_GRID Shape = 11
	// EmbedPayload.
	Shape_SHAPE_EMBED Shape = 12
	// AssetCatalogPayload.
	Shape_SHAPE_ASSET_CATALOG Shape = 13
	// ObjectPayload.
	Shape_SHAPE_OBJECT Shape = 14
	// GraphPayload.
	Shape_SHAPE_GRAPH Shape = 15
	// RepositoryPayload.
	Shape_SHAPE_REPOSITORY Shape = 16
	// RecordSetPayload.
	Shape_SHAPE_RECORD_SET Shape = 17
	// GeoPayload.
	Shape_SHAPE_GEO Shape = 18
	// MediaPayload.
	Shape_SHAPE_MEDIA Shape = 19
	// ConversationPayload.
	Shape_SHAPE_CONVERSATION Shape = 20
	// google.protobuf.Value (DataResponse.json).
	Shape_SHAPE_JSON Shape = 21
)

// Enum value maps for Shape.
var (
	Shape_name = map[int32]string{
		0:  "SHAPE_UNSPECIFIED",
		1:  "SHAPE_TIMESERIES",
		2:  "SHAPE_CANDLES",
		3:  "SHAPE_TABLE",
		4:  "SHAPE_METRIC",
		5:  "SHAPE_GAUGE",
		6:  "SHAPE_HEATMAP",
		7:  "SHAPE_EVENTS",
		8:  "SHAPE_DISTRIBUTION",
		9:  "SHAPE_TEXT",
		10: "SHAPE_ORDERBOOK",
		11: "SHAPE_PAIRED_GRID",
		12: "SHAPE_EMBED",
		13: "SHAPE_ASSET_CATALOG",
		14: "SHAPE_OBJECT",
		15: "SHAPE_GRAPH",
		16: "SHAPE_REPOSITORY",
		17: "SHAPE_RECORD_SET",
		18: "SHAPE_GEO",
		19: "SHAPE_MEDIA",
		20: "SHAPE_CONVERSATION",
		21: "SHAPE_JSON",
	}
	Shape_value = map[string]int32{
		"SHAPE_UNSPECIFIED":   0,
		"SHAPE_TIMESERIES":    1,
		"SHAPE_CANDLES":       2,
		"SHAPE_TABLE":         3,
		"SHAPE_METRIC":        4,
		"SHAPE_GAUGE":         5,
		"SHAPE_HEATMAP":       6,
		"SHAPE_EVENTS":        7,
		"SHAPE_DISTRIBUTION":  8,
		"SHAPE_TEXT":          9,
		"SHAPE_ORDERBOOK":     10,
		"SHAPE_PAIRED_GRID":   11,
		"SHAPE_EMBED":         12,
		"SHAPE_ASSET_CATALOG": 13,
		"SHAPE_OBJECT":        14,
		"SHAPE_GRAPH":         15,
		"SHAPE_REPOSITORY":    16,
		"SHAPE_RECORD_SET":    17,
		"SHAPE_GEO":           18,
		"SHAPE_MEDIA":         19,
		"SHAPE_CONVERSATION":  20,
		"SHAPE_JSON":          21,
	}
)

func (x Shape) Enum() *Shape {
	p := new(Shape)
	*p = x
	return p
}

func (x Shape) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Shape) Descriptor() protoreflect.EnumDescriptor {
	return file_medallion_terminal_v1_terminal_proto_enumTypes[1].Descriptor()
}

func (Shape) Type() protoreflect.EnumType {
	return &file_medallion_terminal_v1_terminal_proto_enumTypes[1]
}

func (x Shape) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Shape.Descriptor instead.
func (Shape) EnumDescriptor() ([]byte, []int) {
	return file_medallion_terminal_v1_terminal_proto_rawDescGZIP(), []int{1}
}

// ActionStatus — coarse lifecycle state of a submitted action.
// Maps cleanly onto common write semantics across domains:
//
//	place_order:  ACCEPTED → PENDING → OK | FAILED | CANCELLED
//	send_message: OK | FAILED
//	swap (web3):  ACCEPTED → PENDING → OK | FAILED
//	vote:         OK | REJECTED
//
// Terminal status: OK, REJECTED, FAILED, CANCELLED — the action will
// not change state again, no need to watch it.
//
// Non-terminal status: ACCEPTED, PENDING — the action will reach a
// terminal state later. Subscribe via WatchAction for updates.
type ActionStatus int32

const (
	// No status declared. Treat as unknown.
	ActionStatus_ACTION_STATUS_UNSPECIFIED ActionStatus = 0
	// Terminal: synchronous success. Action took effect.
	ActionStatus_ACTION_STATUS_OK ActionStatus = 1
	// Non-terminal: acknowledged but not yet acted on (queued,
	// awaiting validation). Watch for a terminal update.
	ActionStatus_ACTION_STATUS_ACCEPTED ActionStatus = 2
	// Non-terminal: in-flight (RPC dispatched, on-chain pending,
	// exchange working). Watch for a terminal update.
	ActionStatus_ACTION_STATUS_PENDING ActionStatus = 3
	// Terminal: refused before execution (validation, auth, business rule).
	ActionStatus_ACTION_STATUS_REJECTED ActionStatus = 4
	// Terminal: attempted and failed (downstream error, exception, revert).
	ActionStatus_ACTION_STATUS_FAILED ActionStatus = 5
	// Terminal: cancelled before completion (by user, timeout, or backend).
	ActionStatus_ACTION_STATUS_CANCELLED ActionStatus = 6
)

// Enum value maps for ActionStatus.
var (
	ActionStatus_name = map[int32]string{
		0: "ACTION_STATUS_UNSPECIFIED",
		1: "ACTION_STATUS_OK",
		2: "ACTION_STATUS_ACCEPTED",
		3: "ACTION_STATUS_PENDING",
		4: "ACTION_STATUS_REJECTED",
		5: "ACTION_STATUS_FAILED",
		6: "ACTION_STATUS_CANCELLED",
	}
	ActionStatus_value = map[string]int32{
		"ACTION_STATUS_UNSPECIFIED": 0,
		"ACTION_STATUS_OK":          1,
		"ACTION_STATUS_ACCEPTED":    2,
		"ACTION_STATUS_PENDING":     3,
		"ACTION_STATUS_REJECTED":    4,
		"ACTION_STATUS_FAILED":      5,
		"ACTION_STATUS_CANCELLED":   6,
	}
)

func (x ActionStatus) Enum() *ActionStatus {
	p := new(ActionStatus)
	*p = x
	return p
}

func (x ActionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_medallion_terminal_v1_terminal_proto_enumTypes[2].Descriptor()
}

func (ActionStatus) Type() protoreflect.EnumType {
	return &file_medallion_terminal_v1_terminal_proto_enumTypes[2]
}

func (x ActionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionStatus.Descriptor instead.
func (ActionStatus) EnumDescriptor() ([]byte, []int) {
	return file_medallion_terminal_v1_terminal_proto_rawDescGZIP(), []int{2}
}

// Request envelope shared by Get and Stream. Selects a source and
// supplies its params.
type DataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Catalog id (matches Source.id from ListSources).
	SourceId string `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// Source-specific params (e.g. "symbol", "range", "window").
	// The frontend substitutes "${ctx.<key>}" tokens before sending.
	Params        map[string]string `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_medallion_terminal_v1_terminal_proto_rawDescGZIP(), []int{0}
}

func (x *DataRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *DataRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// DataResponse always carries exactly one payload. Which case is
// set is determined by the source's declared Shape (see Source).
type DataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one case is set, matching the source's declared Shape.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*DataResponse_Timeseries
	//	*DataResponse_Candles
	//	*DataResponse_Table
	//	*DataResponse_Metric
	//	*DataResponse_Gauge
	//	*DataResponse_Heatmap
	//	*DataResponse_Events
	//	*DataResponse_Distribution
	//	*DataResponse_Text
	//	*DataResponse_Orderbook
	//	*DataResponse_PairedGrid
	//	*DataResponse_Embed
	//	*DataResponse_Assets
	//	*DataResponse_Object
	//	*DataResponse_Graph
	//	*DataResponse_Repository
	//	*DataResponse_Records
	//	*DataResponse_Geo
	//	*DataResponse_Media
	//	*DataResponse_Conversation
	//	*DataResponse_Json
	Payload       isDataResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_medallion_terminal_v1_terminal_proto_rawDescGZIP(), []int{1}
}

func (x *DataResponse) GetPayload() isDataResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DataResponse) GetTimeseries() *TimeseriesPayload {
	if x != nil {
		if x, ok := x.Payload.(*DataResponse_Timeseries); ok {
			return x.Timeseries
		}
	}
	return nil
}

func (x *DataResponse) GetCandles() *CandlePayload {
	if x != nil {
		if x, ok := x.Payload.(*DataResponse_Candles); ok {
			return x.Candles
		}
	}
	return nil
}

func (x *DataResponse) GetTable() *TablePayload {
	if x != nil {
		if x, ok := x.Payload.(*DataResponse_Table); ok {
			return x.Table
		}
	}
	return nil
}

func (x *DataResponse) GetMetric() *MetricPayload {
	if x != nil {
		if x, ok := x.Payload.(*DataResponse_Metric); ok {
			return x.Metric
		}
	}
	return nil
}

func (x *DataResponse) GetGauge() *GaugePayload {
	if x != nil {
		if x, ok := x.Payload.(*DataResponse_Gauge); ok {
			return x.Gauge
		}
	}
	return nil
}

func (x *DataResponse) GetHeatmap() *HeatmapPayload {
	if x != nil {
		if x, ok := x.Payload.(*DataResponse_Heatmap); ok {
			return x.Heatmap
		}
	}
	return nil
}

func (x *DataResponse) GetEvents() *EventPayload {
	if x != nil {
		if x, ok := x.Payload.(*DataResponse_Events); ok {
			return x.Events
		}
	}
	return nil
}

func (x *DataResponse) GetDistribution() *DistributionPayload {
	if x != nil {
		if x, ok := x.Payload.(*DataResponse_Distribution); ok {
			return x.Distribution
		}
	}
	return nil
}

func (x *DataResponse) GetText() *TextPayload {
	if x != nil {
		if x, ok := x.Payload.(*DataResponse_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *DataResponse) GetOrderbook() *OrderBookPayload {
	if x != nil {
		if x, ok := x.Payload.(*DataResponse_Orderbook); ok {
			return x.Orderbook
		}
	}
	return nil
}

func (x *DataResponse) GetPairedGrid() *PairedGridPayload {
	if x != nil {
		if x, ok := x.Payload.(*DataResponse_PairedGrid); ok {
			return x.PairedGrid
		}
	}
	return nil
}

func (x *DataResponse) GetEmbed() *EmbedPayload {
	if x != nil {
		if x, ok := x.Payload.(*DataResponse_Embed); ok {
			return x.Embed
		}
	}
	return nil
}

func (x *DataResponse) GetAssets() *AssetCatalogPayload {
	if x != nil {
		if x, ok := x.Payload.(*DataResponse_Assets); ok {
			return x.Assets
		}
	}
	return nil
}

func (x *DataResponse) GetObject() *ObjectPayload {
	if x != nil {
		if x, ok := x.Payload.(*DataResponse_Object); ok {
			return x.Object
		}
	}
	return nil
}

func (x *DataResponse) GetGraph() *GraphPayload {
	if x != nil {
		if x, ok := x.Payload.(*DataResponse_Graph); ok {
			return x.Graph
		}
	}
	return nil
}

func (x *DataResponse) GetRepository() *RepositoryPayload {
	if x != nil {
		if x, ok := x.Payload.(*DataResponse_Repository); ok {
			return x.Repository
		}
	}
	return nil
}

func (x *DataResponse) GetRecords() *RecordSetPayload {
	if x != nil {
		if x, ok := x.Payload.(*DataResponse_Records); ok {
			return x.Records
		}
	}
	return nil
}

func (x *DataResponse) GetGeo() *GeoPayload {
	if x != nil {
		if x, ok := x.Payload.(*DataResponse_Geo); ok {
			return x.Geo
		}
	}
	return nil
}

func (x *DataResponse) GetMedia() *MediaPayload {
	if x != nil {
		if x, ok := x.Payload.(*DataResponse_Media); ok {
			return x.Media
		}
	}
	return nil
}

func (x *DataResponse) GetConversation() *ConversationPayload {
	if x != nil {
		if x, ok := x.Payload.(*DataResponse_Conversation); ok {
			return x.Conversation
		}
	}
	return nil
}

func (x *DataResponse) GetJson() *structpb.Value {
	if x != nil {
		if x, ok := x.Payload.(*DataResponse_Json); ok {
			return x.Json
		}
	}
	return nil
}

type isDataResponse_Payload interface {
	isDataResponse_Payload()
}

type DataResponse_Timeseries struct {
	// Line-chart data. See TimeseriesPayload.
	Timeseries *TimeseriesPayload `protobuf:"bytes,1,opt,name=timeseries,proto3,oneof"`
}

type DataResponse_Candles struct {
	// OHLCV bars. See CandlePayload.
	Candles *CandlePayload `protobuf:"bytes,2,opt,name=candles,proto3,oneof"`
}

type DataResponse_Table struct {
	// Tabular rows. See TablePayload.
	Table *TablePayload `protobuf:"bytes,3,opt,name=table,proto3,oneof"`
}

type DataResponse_Metric struct {
	// Single headline number. See MetricPayload.
	Metric *MetricPayload `protobuf:"bytes,4,opt,name=metric,proto3,oneof"`
}

type DataResponse_Gauge struct {
	// Bounded scalar. See GaugePayload.
	Gauge *GaugePayload `protobuf:"bytes,5,opt,name=gauge,proto3,oneof"`
}

type DataResponse_Heatmap struct {
	// 2D matrix. See HeatmapPayload.
	Heatmap *HeatmapPayload `protobuf:"bytes,6,opt,name=heatmap,proto3,oneof"`
}

type DataResponse_Events struct {
	// Status timeline. See EventPayload.
	Events *EventPayload `protobuf:"bytes,7,opt,name=events,proto3,oneof"`
}

type DataResponse_Distribution struct {
	// Categorical proportions. See DistributionPayload.
	Distribution *DistributionPayload `protobuf:"bytes,8,opt,name=distribution,proto3,oneof"`
}

type DataResponse_Text struct {
	// News/summary items. See TextPayload.
	Text *TextPayload `protobuf:"bytes,9,opt,name=text,proto3,oneof"`
}

type DataResponse_Orderbook struct {
	// Bid/ask depth. See OrderBookPayload.
	Orderbook *OrderBookPayload `protobuf:"bytes,10,opt,name=orderbook,proto3,oneof"`
}

type DataResponse_PairedGrid struct {
	// Left/right lattice. See PairedGridPayload.
	PairedGrid *PairedGridPayload `protobuf:"bytes,11,opt,name=paired_grid,json=pairedGrid,proto3,oneof"`
}

type DataResponse_Embed struct {
	// Context-driven image/iframe URL. See EmbedPayload.
	Embed *EmbedPayload `protobuf:"bytes,12,opt,name=embed,proto3,oneof"`
}

type DataResponse_Assets struct {
	// Catalog of platform assets. See AssetCatalogPayload.
	Assets *AssetCatalogPayload `protobuf:"bytes,13,opt,name=assets,proto3,oneof"`
}

type DataResponse_Object struct {
	// Ontology object detail. See ObjectPayload.
	Object *ObjectPayload `protobuf:"bytes,14,opt,name=object,proto3,oneof"`
}

type DataResponse_Graph struct {
	// Directed graph. See GraphPayload.
	Graph *GraphPayload `protobuf:"bytes,15,opt,name=graph,proto3,oneof"`
}

type DataResponse_Repository struct {
	// Source browsing. See RepositoryPayload.
	Repository *RepositoryPayload `protobuf:"bytes,16,opt,name=repository,proto3,oneof"`
}

type DataResponse_Records struct {
	// Mutable record set. See RecordSetPayload.
	Records *RecordSetPayload `protobuf:"bytes,17,opt,name=records,proto3,oneof"`
}

type DataResponse_Geo struct {
	// Geospatial features. See GeoPayload.
	Geo *GeoPayload `protobuf:"bytes,18,opt,name=geo,proto3,oneof"`
}

type DataResponse_Media struct {
	// Media library. See MediaPayload.
	Media *MediaPayload `protobuf:"bytes,19,opt,name=media,proto3,oneof"`
}

type DataResponse_Conversation struct {
	// Message transcript. See ConversationPayload.
	Conversation *ConversationPayload `protobuf:"bytes,20,opt,name=conversation,proto3,oneof"`
}

type DataResponse_Json struct {
	// Any JSON document for the `json` widget: the ProtoJSON of a message the
	// backend decoded with its own descriptors, or a plain document. The
	// frontend renders it verbatim and never interprets it.
	Json *structpb.Value `protobuf:"bytes,21,opt,name=json,proto3,oneof"`
}

func (*DataResponse_Timeseries) isDataResponse_Payload() {}

func (*DataResponse_Candles) isDataResponse_Payload() {}

func (*DataResponse_Table) isDataResponse_Payload() {}

func (*DataResponse_Metric) isDataResponse_Payload() {}

func (*DataResponse_Gauge) isDataResponse_Payload() {}

func (*DataResponse_Heatmap) isDataResponse_Payload() {}

func (*DataResponse_Events) isDataResponse_Payload() {}

func (*DataResponse_Distribution) isDataResponse_Payload() {}

func (*DataResponse_Text) isDataResponse_Payload() {}

func (*DataResponse_Orderbook) isDataResponse_Payload() {}

func (*DataResponse_PairedGrid) isDataResponse_Payload() {}

func (*DataResponse_Embed) isDataResponse_Payload() {}

func (*DataResponse_Assets) isDataResponse_Payload() {}

func (*DataResponse_Object) isDataResponse_Payload() {}

func (*DataResponse_Graph) isDataResponse_Payload() {}

func (*DataResponse_Repository) isDataResponse_Payload() {}

func (*DataResponse_Records) isDataResponse_Payload() {}

func (*DataResponse_Geo) isDataResponse_Payload() {}

func (*DataResponse_Media) isDataResponse_Payload() {}

func (*DataResponse_Conversation) isDataResponse_Payload() {}

func (*DataResponse_Json) isDataResponse_Payload() {}

// ListSourcesRequest carries no fields today; filtering may be
// added later.
type ListSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSourcesRequest) Reset() {
	*x = ListSourcesRequest{}
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourcesRequest) ProtoMessage() {}

func (x *ListSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourcesRequest.ProtoReflect.Descriptor instead.
func (*ListSourcesRequest) Descriptor() ([]byte, []int) {
	return file_medallion_terminal_v1_terminal_proto_rawDescGZIP(), []int{2}
}

// The backend's full source catalog.
type ListSourcesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Every source the backend can serve.
	Sources       []*Source `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSourcesResponse) Reset() {
	*x = ListSourcesResponse{}
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourcesResponse) ProtoMessage() {}

func (x *ListSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListSourcesResponse) Descriptor() ([]byte, []int) {
	return file_medallion_terminal_v1_terminal_proto_rawDescGZIP(), []int{3}
}

func (x *ListSourcesResponse) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

// Source describes one registered data provider on the backend.
//
// A backend's source catalog is its public surface: every entry
// here is something a dashboard widget (or the AI) can ask for.
type Source struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable id used by DataRequest.source_id and DataSource.source_id.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable display name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// What this source returns, in plain language. Read by the AI
	// when deciding which sources to wire into a generated dashboard.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Which payload variant Get/Stream returns for this source.
	Shape Shape `protobuf:"varint,4,opt,name=shape,proto3,enum=medallion.terminal.v1.Shape" json:"shape,omitempty"`
	// Declared parameters this source accepts.
	Params []*SourceParam `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty"`
	// True if the source supports the Stream RPC. Get is always
	// assumed available.
	Streamable bool `protobuf:"varint,6,opt,name=streamable,proto3" json:"streamable,omitempty"`
	// Free-form tags for grouping in catalog UIs and search
	// (e.g. "crypto", "sentiment", "ops", "prediction").
	Tags          []string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_medallion_terminal_v1_terminal_proto_rawDescGZIP(), []int{4}
}

func (x *Source) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Source) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Source) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Source) GetShape() Shape {
	if x != nil {
		return x.Shape
	}
	return Shape_SHAPE_UNSPECIFIED
}

func (x *Source) GetParams() []*SourceParam {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Source) GetStreamable() bool {
	if x != nil {
		return x.Streamable
	}
	return false
}

func (x *Source) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// SourceParam declares one parameter a Source accepts.
type SourceParam struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Param key (matches DataRequest.params keys).
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Human description, read by AI and shown in catalog UIs.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// True if the source rejects requests missing this param.
	Required bool `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	// Default value if omitted by the caller. Always serialized as
	// a string regardless of `type`; the backend parses per `type`.
	DefaultValue string `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	// If non-empty, the param is constrained to these values. Only
	// meaningful when type is unspecified or PARAM_TYPE_ENUM.
	EnumValues []string `protobuf:"bytes,5,rep,name=enum_values,json=enumValues,proto3" json:"enum_values,omitempty"`
	// Value type. Drives input rendering in catalog/authoring UIs and
	// tells the AI how to format substitutions. Values still travel
	// over the wire as strings (params is map<string,string>); the
	// backend parses based on this type.
	Type ParamType `protobuf:"varint,6,opt,name=type,proto3,enum=medallion.terminal.v1.ParamType" json:"type,omitempty"`
	// Multi-value param. When true, the wire value is comma-separated
	// (e.g. params["symbols"] = "BTC,ETH,SOL") and the backend splits
	// before parsing. Combine with type to constrain element types and
	// with enum_values to constrain element membership.
	Repeated      bool `protobuf:"varint,7,opt,name=repeated,proto3" json:"repeated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceParam) Reset() {
	*x = SourceParam{}
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceParam) ProtoMessage() {}

func (x *SourceParam) ProtoReflect() protoreflect.Message {
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceParam.ProtoReflect.Descriptor instead.
func (*SourceParam) Descriptor() ([]byte, []int) {
	return file_medallion_terminal_v1_terminal_proto_rawDescGZIP(), []int{5}
}

func (x *SourceParam) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SourceParam) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SourceParam) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *SourceParam) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *SourceParam) GetEnumValues() []string {
	if x != nil {
		return x.EnumValues
	}
	return nil
}

func (x *SourceParam) GetType() ParamType {
	if x != nil {
		return x.Type
	}
	return ParamType_PARAM_TYPE_UNSPECIFIED
}

func (x *SourceParam) GetRepeated() bool {
	if x != nil {
		return x.Repeated
	}
	return false
}

// Input to the AI Generate RPC.
type GenerateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user's natural-language prompt
	// (e.g. "how's bitcoin today?", "show me bot pnl this week").
	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// The dashboard's current context. The model can reference these
	// values when emitting widgets (e.g. keep the existing symbol).
	Context *Context `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	// The widgets currently on screen, so the model can choose
	// between surgical edits and a full rebuild. Optional.
	CurrentWidgets []*Widget `protobuf:"bytes,3,rep,name=current_widgets,json=currentWidgets,proto3" json:"current_widgets,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_medallion_terminal_v1_terminal_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GenerateRequest) GetCurrentWidgets() []*Widget {
	if x != nil {
		return x.CurrentWidgets
	}
	return nil
}

// Output of the AI Generate RPC: a reply plus dashboard mutations.
type GenerateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Assistant reply shown to the user (a one-sentence summary or
	// explanation of what was wired up).
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Mutations to apply to the dashboard. Each action targets a
	// widget by id; absent ids cause creation
	// (see template.proto WidgetAction semantics).
	Actions []*WidgetAction `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	// If true, drop all existing widgets before applying actions —
	// signals a full dashboard rebuild rather than a surgical edit.
	// The AI decides this based on the prompt.
	ReplaceAll bool `protobuf:"varint,3,opt,name=replace_all,json=replaceAll,proto3" json:"replace_all,omitempty"`
	// Optional context updates emitted by the AI (e.g. user said
	// "switch to ETH" — model returns context update {symbol:"ETH"}
	// alongside any widget tweaks).
	Context       *Context `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_medallion_terminal_v1_terminal_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GenerateResponse) GetActions() []*WidgetAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *GenerateResponse) GetReplaceAll() bool {
	if x != nil {
		return x.ReplaceAll
	}
	return false
}

func (x *GenerateResponse) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

// Generic write-side dispatch. The framework's read RPCs (Get / Stream
// / ListSources / Generate) cover query and AI flows; SubmitAction
// covers everything that mutates state on the backend — placing an
// order, executing a swap, casting a vote, sending a message.
//
// The `action_id` selects the handler. Common ids by convention:
//
//	"place_order"   — params: {symbol, side, amount, price?, type}
//	"swap"          — params: {from_token, to_token, amount, ...}
//	"send_message"  — params: {to, body}
//
// `params` is intentionally a generic Struct to keep the dispatch
// surface domain-agnostic. Each action defines its own param schema
// in the backend's documentation; widgets that submit actions know
// the shape by convention.
type ActionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Selects the backend handler (e.g. "place_order").
	ActionId string `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	// Action parameters. Schema is per-action by convention.
	Params *structpb.Struct `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	// Client-generated idempotency key. The backend MUST treat repeated
	// requests with the same client_request_id as the same action and
	// return the original response — critical for retry loops, network
	// hiccups, and double-clicks on submit buttons. Recommended: a
	// UUIDv4 generated when the user clicks submit. Empty string =
	// no idempotency, treat each call as new.
	ClientRequestId string `protobuf:"bytes,3,opt,name=client_request_id,json=clientRequestId,proto3" json:"client_request_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_medallion_terminal_v1_terminal_proto_rawDescGZIP(), []int{8}
}

func (x *ActionRequest) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ActionRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ActionRequest) GetClientRequestId() string {
	if x != nil {
		return x.ClientRequestId
	}
	return ""
}

// Backend acknowledgement of a submitted action.
//
// `status` is the coarse lifecycle state. Action-specific finer
// states (an order's "filled" vs "partial", a workflow's "stage 2 of 4")
// go in `status_detail` so dashboards can render them without
// inventing per-action enums.
type ActionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Backend-assigned id (order id, message id, etc.). Useful for
	// client-side reconciliation against later Stream / Events updates.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Coarse lifecycle state. See ActionStatus for semantics.
	Status ActionStatus `protobuf:"varint,2,opt,name=status,proto3,enum=medallion.terminal.v1.ActionStatus" json:"status,omitempty"`
	// Human-readable message — shown to the user as a toast on the
	// submitting widget.
	Message *string `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	// Optional structured payload (e.g. filled price, gas cost, tx hash).
	Data *structpb.Struct `protobuf:"bytes,4,opt,name=data,proto3,oneof" json:"data,omitempty"`
	// Action-specific sub-state when ActionStatus alone is too coarse
	// (e.g. "partial", "filled", "stage_2_of_4"). Free-form by
	// convention — widgets that care interpret it; others ignore.
	StatusDetail  *string `protobuf:"bytes,5,opt,name=status_detail,json=statusDetail,proto3,oneof" json:"status_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_medallion_terminal_v1_terminal_proto_rawDescGZIP(), []int{9}
}

func (x *ActionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionResponse) GetStatus() ActionStatus {
	if x != nil {
		return x.Status
	}
	return ActionStatus_ACTION_STATUS_UNSPECIFIED
}

func (x *ActionResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ActionResponse) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ActionResponse) GetStatusDetail() string {
	if x != nil && x.StatusDetail != nil {
		return *x.StatusDetail
	}
	return ""
}

// ActionWatchRequest — subscribe to lifecycle updates for one action.
// Identify the action by any of the three keys; at least one must be
// set. client_request_id is the most useful for client-side retry
// reconciliation, since the client knows it before the backend
// responds.
type ActionWatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The action_id originally passed to SubmitAction (e.g. "place_order").
	ActionId string `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	// The backend-assigned id from ActionResponse.id.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// The client-generated idempotency key from ActionRequest.client_request_id.
	ClientRequestId string `protobuf:"bytes,3,opt,name=client_request_id,json=clientRequestId,proto3" json:"client_request_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActionWatchRequest) Reset() {
	*x = ActionWatchRequest{}
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionWatchRequest) ProtoMessage() {}

func (x *ActionWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionWatchRequest.ProtoReflect.Descriptor instead.
func (*ActionWatchRequest) Descriptor() ([]byte, []int) {
	return file_medallion_terminal_v1_terminal_proto_rawDescGZIP(), []int{10}
}

func (x *ActionWatchRequest) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ActionWatchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionWatchRequest) GetClientRequestId() string {
	if x != nil {
		return x.ClientRequestId
	}
	return ""
}

// ActionUpdate — one lifecycle event for a watched action. The
// stream emits one of these every time the action's state advances
// (queued → working → filled, etc.). The stream closes after the
// first ActionUpdate with a terminal ActionStatus.
type ActionUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Backend-assigned id (mirrors ActionResponse.id).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The action handler this update belongs to (mirrors ActionRequest.action_id).
	ActionId string `protobuf:"bytes,2,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	// Mirrors ActionRequest.client_request_id, so clients can
	// reconcile updates with their in-flight submit calls.
	ClientRequestId string `protobuf:"bytes,3,opt,name=client_request_id,json=clientRequestId,proto3" json:"client_request_id,omitempty"`
	// Current lifecycle state. The stream closes after the first
	// update with a terminal status.
	Status ActionStatus `protobuf:"varint,4,opt,name=status,proto3,enum=medallion.terminal.v1.ActionStatus" json:"status,omitempty"`
	// Action-specific sub-state ("partial", "filled", "stage_2_of_4").
	StatusDetail *string `protobuf:"bytes,5,opt,name=status_detail,json=statusDetail,proto3,oneof" json:"status_detail,omitempty"`
	// Human-readable message — surfaced to the user as a toast.
	Message *string `protobuf:"bytes,6,opt,name=message,proto3,oneof" json:"message,omitempty"`
	// Optional structured payload (filled price, gas cost, tx hash,
	// confirmations).
	Data *structpb.Struct `protobuf:"bytes,7,opt,name=data,proto3,oneof" json:"data,omitempty"`
	// ISO 8601 timestamp the backend emitted this update.
	Timestamp string `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Monotonic per-action counter starting at 0. Lets clients
	// detect dropped messages and reorder if a transport reorders.
	Sequence      uint64 `protobuf:"varint,9,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionUpdate) Reset() {
	*x = ActionUpdate{}
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionUpdate) ProtoMessage() {}

func (x *ActionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_medallion_terminal_v1_terminal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionUpdate.ProtoReflect.Descriptor instead.
func (*ActionUpdate) Descriptor() ([]byte, []int) {
	return file_medallion_terminal_v1_terminal_proto_rawDescGZIP(), []int{11}
}

func (x *ActionUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionUpdate) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ActionUpdate) GetClientRequestId() string {
	if x != nil {
		return x.ClientRequestId
	}
	return ""
}

func (x *ActionUpdate) GetStatus() ActionStatus {
	if x != nil {
		return x.Status
	}
	return ActionStatus_ACTION_STATUS_UNSPECIFIED
}

func (x *ActionUpdate) GetStatusDetail() string {
	if x != nil && x.StatusDetail != nil {
		return *x.StatusDetail
	}
	return ""
}

func (x *ActionUpdate) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ActionUpdate) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ActionUpdate) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ActionUpdate) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_medallion_terminal_v1_terminal_proto protoreflect.FileDescriptor

const file_medallion_terminal_v1_terminal_proto_rawDesc = "" +
	"\n" +
	"$medallion/terminal/v1/terminal.proto\x12\x15medallion.terminal.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\"medallion/terminal/v1/shapes.proto\x1a$medallion/terminal/v1/template.proto\"\xad\x01\n" +
	"\vDataRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12F\n" +
	"\x06params\x18\x02 \x03(\v2..medallion.terminal.v1.DataRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\v\n" +
	"\fDataResponse\x12J\n" +
	"\n" +
	"timeseries\x18\x01 \x01(\v2(.medallion.terminal.v1.TimeseriesPayloadH\x00R\n" +
	"timeseries\x12@\n" +
	"\acandles\x18\x02 \x01(\v2$.medallion.terminal.v1.CandlePayloadH\x00R\acandles\x12;\n" +
	"\x05table\x18\x03 \x01(\v2#.medallion.terminal.v1.TablePayloadH\x00R\x05table\x12>\n" +
	"\x06metric\x18\x04 \x01(\v2$.medallion.terminal.v1.MetricPayloadH\x00R\x06metric\x12;\n" +
	"\x05gauge\x18\x05 \x01(\v2#.medallion.terminal.v1.GaugePayloadH\x00R\x05gauge\x12A\n" +
	"\aheatmap\x18\x06 \x01(\v2%.medallion.terminal.v1.HeatmapPayloadH\x00R\aheatmap\x12=\n" +
	"\x06events\x18\a \x01(\v2#.medallion.terminal.v1.EventPayloadH\x00R\x06events\x12P\n" +
	"\fdistribution\x18\b \x01(\v2*.medallion.terminal.v1.DistributionPayloadH\x00R\fdistribution\x128\n" +
	"\x04text\x18\t \x01(\v2\".medallion.terminal.v1.TextPayloadH\x00R\x04text\x12G\n" +
	"\torderbook\x18\n" +
	" \x01(\v2'.medallion.terminal.v1.OrderBookPayloadH\x00R\torderbook\x12K\n" +
	"\vpaired_grid\x18\v \x01(\v2(.medallion.terminal.v1.PairedGridPayloadH\x00R\n" +
	"pairedGrid\x12;\n" +
	"\x05embed\x18\f \x01(\v2#.medallion.terminal.v1.EmbedPayloadH\x00R\x05embed\x12D\n" +
	"\x06assets\x18\r \x01(\v2*.medallion.terminal.v1.AssetCatalogPayloadH\x00R\x06assets\x12>\n" +
	"\x06object\x18\x0e \x01(\v2$.medallion.terminal.v1.ObjectPayloadH\x00R\x06object\x12;\n" +
	"\x05graph\x18\x0f \x01(\v2#.medallion.terminal.v1.GraphPayloadH\x00R\x05graph\x12J\n" +
	"\n" +
	"repository\x18\x10 \x01(\v2(.medallion.terminal.v1.RepositoryPayloadH\x00R\n" +
	"repository\x12C\n" +
	"\arecords\x18\x11 \x01(\v2'.medallion.terminal.v1.RecordSetPayloadH\x00R\arecords\x125\n" +
	"\x03geo\x18\x12 \x01(\v2!.medallion.terminal.v1.GeoPayloadH\x00R\x03geo\x12;\n" +
	"\x05media\x18\x13 \x01(\v2#.medallion.terminal.v1.MediaPayloadH\x00R\x05media\x12P\n" +
	"\fconversation\x18\x14 \x01(\v2*.medallion.terminal.v1.ConversationPayloadH\x00R\fconversation\x12,\n" +
	"\x04json\x18\x15 \x01(\v2\x16.google.protobuf.ValueH\x00R\x04jsonB\t\n" +
	"\apayload\"\x14\n" +
	"\x12ListSourcesRequest\"N\n" +
	"\x13ListSourcesResponse\x127\n" +
	"\asources\x18\x01 \x03(\v2\x1d.medallion.terminal.v1.SourceR\asources\"\xf2\x01\n" +
	"\x06Source\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x122\n" +
	"\x05shape\x18\x04 \x01(\x0e2\x1c.medallion.terminal.v1.ShapeR\x05shape\x12:\n" +
	"\x06params\x18\x05 \x03(\v2\".medallion.terminal.v1.SourceParamR\x06params\x12\x1e\n" +
	"\n" +
	"streamable\x18\x06 \x01(\bR\n" +
	"streamable\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\"\xf5\x01\n" +
	"\vSourceParam\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12#\n" +
	"\rdefault_value\x18\x04 \x01(\tR\fdefaultValue\x12\x1f\n" +
	"\venum_values\x18\x05 \x03(\tR\n" +
	"enumValues\x124\n" +
	"\x04type\x18\x06 \x01(\x0e2 .medallion.terminal.v1.ParamTypeR\x04type\x12\x1a\n" +
	"\brepeated\x18\a \x01(\bR\brepeated\"\xab\x01\n" +
	"\x0fGenerateRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x128\n" +
	"\acontext\x18\x02 \x01(\v2\x1e.medallion.terminal.v1.ContextR\acontext\x12F\n" +
	"\x0fcurrent_widgets\x18\x03 \x03(\v2\x1d.medallion.terminal.v1.WidgetR\x0ecurrentWidgets\"\xc0\x01\n" +
	"\x10GenerateResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12=\n" +
	"\aactions\x18\x02 \x03(\v2#.medallion.terminal.v1.WidgetActionR\aactions\x12\x1f\n" +
	"\vreplace_all\x18\x03 \x01(\bR\n" +
	"replaceAll\x128\n" +
	"\acontext\x18\x04 \x01(\v2\x1e.medallion.terminal.v1.ContextR\acontext\"\x89\x01\n" +
	"\rActionRequest\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12/\n" +
	"\x06params\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06params\x12*\n" +
	"\x11client_request_id\x18\x03 \x01(\tR\x0fclientRequestId\"\xff\x01\n" +
	"\x0eActionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2#.medallion.terminal.v1.ActionStatusR\x06status\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x00R\amessage\x88\x01\x01\x120\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x01R\x04data\x88\x01\x01\x12(\n" +
	"\rstatus_detail\x18\x05 \x01(\tH\x02R\fstatusDetail\x88\x01\x01B\n" +
	"\n" +
	"\b_messageB\a\n" +
	"\x05_dataB\x10\n" +
	"\x0e_status_detail\"m\n" +
	"\x12ActionWatchRequest\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12*\n" +
	"\x11client_request_id\x18\x03 \x01(\tR\x0fclientRequestId\"\x80\x03\n" +
	"\fActionUpdate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\taction_id\x18\x02 \x01(\tR\bactionId\x12*\n" +
	"\x11client_request_id\x18\x03 \x01(\tR\x0fclientRequestId\x12;\n" +
	"\x06status\x18\x04 \x01(\x0e2#.medallion.terminal.v1.ActionStatusR\x06status\x12(\n" +
	"\rstatus_detail\x18\x05 \x01(\tH\x00R\fstatusDetail\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x06 \x01(\tH\x01R\amessage\x88\x01\x01\x120\n" +
	"\x04data\x18\a \x01(\v2\x17.google.protobuf.StructH\x02R\x04data\x88\x01\x01\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\tR\ttimestamp\x12\x1a\n" +
	"\bsequence\x18\t \x01(\x04R\bsequenceB\x10\n" +
	"\x0e_status_detailB\n" +
	"\n" +
	"\b_messageB\a\n" +
	"\x05_data*\xe2\x01\n" +
	"\tParamType\x12\x1a\n" +
	"\x16PARAM_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PARAM_TYPE_STRING\x10\x01\x12\x15\n" +
	"\x11PARAM_TYPE_NUMBER\x10\x02\x12\x16\n" +
	"\x12PARAM_TYPE_BOOLEAN\x10\x03\x12\x18\n" +
	"\x14PARAM_TYPE_TIMESTAMP\x10\x04\x12\x17\n" +
	"\x13PARAM_TYPE_DURATION\x10\x05\x12\x13\n" +
	"\x0fPARAM_TYPE_ENUM\x10\x06\x12\x16\n" +
	"\x12PARAM_TYPE_INTEGER\x10\a\x12\x13\n" +
	"\x0fPARAM_TYPE_DATE\x10\b*\xb5\x03\n" +
	"\x05Shape\x12\x15\n" +
	"\x11SHAPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SHAPE_TIMESERIES\x10\x01\x12\x11\n" +
	"\rSHAPE_CANDLES\x10\x02\x12\x0f\n" +
	"\vSHAPE_TABLE\x10\x03\x12\x10\n" +
	"\fSHAPE_METRIC\x10\x04\x12\x0f\n" +
	"\vSHAPE_GAUGE\x10\x05\x12\x11\n" +
	"\rSHAPE_HEATMAP\x10\x06\x12\x10\n" +
	"\fSHAPE_EVENTS\x10\a\x12\x16\n" +
	"\x12SHAPE_DISTRIBUTION\x10\b\x12\x0e\n" +
	"\n" +
	"SHAPE_TEXT\x10\t\x12\x13\n" +
	"\x0fSHAPE_ORDERBOOK\x10\n" +
	"\x12\x15\n" +
	"\x11SHAPE_PAIRED_GRID\x10\v\x12\x0f\n" +
	"\vSHAPE_EMBED\x10\f\x12\x17\n" +
	"\x13SHAPE_ASSET_CATALOG\x10\r\x12\x10\n" +
	"\fSHAPE_OBJECT\x10\x0e\x12\x0f\n" +
	"\vSHAPE_GRAPH\x10\x0f\x12\x14\n" +
	"\x10SHAPE_REPOSITORY\x10\x10\x12\x14\n" +
	"\x10SHAPE_RECORD_SET\x10\x11\x12\r\n" +
	"\tSHAPE_GEO\x10\x12\x12\x0f\n" +
	"\vSHAPE_MEDIA\x10\x13\x12\x16\n" +
	"\x12SHAPE_CONVERSATION\x10\x14\x12\x0e\n" +
	"\n" +
	"SHAPE_JSON\x10\x15*\xcd\x01\n" +
	"\fActionStatus\x12\x1d\n" +
	"\x19ACTION_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ACTION_STATUS_OK\x10\x01\x12\x1a\n" +
	"\x16ACTION_STATUS_ACCEPTED\x10\x02\x12\x19\n" +
	"\x15ACTION_STATUS_PENDING\x10\x03\x12\x1a\n" +
	"\x16ACTION_STATUS_REJECTED\x10\x04\x12\x18\n" +
	"\x14ACTION_STATUS_FAILED\x10\x05\x12\x1b\n" +
	"\x17ACTION_STATUS_CANCELLED\x10\x062\xb7\x04\n" +
	"\x0fTerminalService\x12N\n" +
	"\x03Get\x12\".medallion.terminal.v1.DataRequest\x1a#.medallion.terminal.v1.DataResponse\x12S\n" +
	"\x06Stream\x12\".medallion.terminal.v1.DataRequest\x1a#.medallion.terminal.v1.DataResponse0\x01\x12d\n" +
	"\vListSources\x12).medallion.terminal.v1.ListSourcesRequest\x1a*.medallion.terminal.v1.ListSourcesResponse\x12[\n" +
	"\bGenerate\x12&.medallion.terminal.v1.GenerateRequest\x1a'.medallion.terminal.v1.GenerateResponse\x12[\n" +
	"\fSubmitAction\x12$.medallion.terminal.v1.ActionRequest\x1a%.medallion.terminal.v1.ActionResponse\x12_\n" +
	"\vWatchAction\x12).medallion.terminal.v1.ActionWatchRequest\x1a#.medallion.terminal.v1.ActionUpdate0\x01b\x06proto3"

var (
	file_medallion_terminal_v1_terminal_proto_rawDescOnce sync.Once
	file_medallion_terminal_v1_terminal_proto_rawDescData []byte
)

func file_medallion_terminal_v1_terminal_proto_rawDescGZIP() []byte {
	file_medallion_terminal_v1_terminal_proto_rawDescOnce.Do(func() {
		file_medallion_terminal_v1_terminal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_medallion_terminal_v1_terminal_proto_rawDesc), len(file_medallion_terminal_v1_terminal_proto_rawDesc)))
	})
	return file_medallion_terminal_v1_terminal_proto_rawDescData
}

var file_medallion_terminal_v1_terminal_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_medallion_terminal_v1_terminal_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_medallion_terminal_v1_terminal_proto_goTypes = []any{
	(ParamType)(0),              // 0: medallion.terminal.v1.ParamType
	(Shape)(0),                  // 1: medallion.terminal.v1.Shape
	(ActionStatus)(0),           // 2: medallion.terminal.v1.ActionStatus
	(*DataRequest)(nil),         // 3: medallion.terminal.v1.DataRequest
	(*DataResponse)(nil),        // 4: medallion.terminal.v1.DataResponse
	(*ListSourcesRequest)(nil),  // 5: medallion.terminal.v1.ListSourcesRequest
	(*ListSourcesResponse)(nil), // 6: medallion.terminal.v1.ListSourcesResponse
	(*Source)(nil),              // 7: medallion.terminal.v1.Source
	(*SourceParam)(nil),         // 8: medallion.terminal.v1.SourceParam
	(*GenerateRequest)(nil),     // 9: medallion.terminal.v1.GenerateRequest
	(*GenerateResponse)(nil),    // 10: medallion.terminal.v1.GenerateResponse
	(*ActionRequest)(nil),       // 11: medallion.terminal.v1.ActionRequest
	(*ActionResponse)(nil),      // 12: medallion.terminal.v1.ActionResponse
	(*ActionWatchRequest)(nil),  // 13: medallion.terminal.v1.ActionWatchRequest
	(*ActionUpdate)(nil),        // 14: medallion.terminal.v1.ActionUpdate
	nil,                         // 15: medallion.terminal.v1.DataRequest.ParamsEntry
	(*TimeseriesPayload)(nil),   // 16: medallion.terminal.v1.TimeseriesPayload
	(*CandlePayload)(nil),       // 17: medallion.terminal.v1.CandlePayload
	(*TablePayload)(nil),        // 18: medallion.terminal.v1.TablePayload
	(*MetricPayload)(nil),       // 19: medallion.terminal.v1.MetricPayload
	(*GaugePayload)(nil),        // 20: medallion.terminal.v1.GaugePayload
	(*HeatmapPayload)(nil),      // 21: medallion.terminal.v1.HeatmapPayload
	(*EventPayload)(nil),        // 22: medallion.terminal.v1.EventPayload
	(*DistributionPayload)(nil), // 23: medallion.terminal.v1.DistributionPayload
	(*TextPayload)(nil),         // 24: medallion.terminal.v1.TextPayload
	(*OrderBookPayload)(nil),    // 25: medallion.terminal.v1.OrderBookPayload
	(*PairedGridPayload)(nil),   // 26: medallion.terminal.v1.PairedGridPayload
	(*EmbedPayload)(nil),        // 27: medallion.terminal.v1.EmbedPayload
	(*AssetCatalogPayload)(nil), // 28: medallion.terminal.v1.AssetCatalogPayload
	(*ObjectPayload)(nil),       // 29: medallion.terminal.v1.ObjectPayload
	(*GraphPayload)(nil),        // 30: medallion.terminal.v1.GraphPayload
	(*RepositoryPayload)(nil),   // 31: medallion.terminal.v1.RepositoryPayload
	(*RecordSetPayload)(nil),    // 32: medallion.terminal.v1.RecordSetPayload
	(*GeoPayload)(nil),          // 33: medallion.terminal.v1.GeoPayload
	(*MediaPayload)(nil),        // 34: medallion.terminal.v1.MediaPayload
	(*ConversationPayload)(nil), // 35: medallion.terminal.v1.ConversationPayload
	(*structpb.Value)(nil),      // 36: google.protobuf.Value
	(*Context)(nil),             // 37: medallion.terminal.v1.Context
	(*Widget)(nil),              // 38: medallion.terminal.v1.Widget
	(*WidgetAction)(nil),        // 39: medallion.terminal.v1.WidgetAction
	(*structpb.Struct)(nil),     // 40: google.protobuf.Struct
}
var file_medallion_terminal_v1_terminal_proto_depIdxs = []int32{
	15, // 0: medallion.terminal.v1.DataRequest.params:type_name -> medallion.terminal.v1.DataRequest.ParamsEntry
	16, // 1: medallion.terminal.v1.DataResponse.timeseries:type_name -> medallion.terminal.v1.TimeseriesPayload
	17, // 2: medallion.terminal.v1.DataResponse.candles:type_name -> medallion.terminal.v1.CandlePayload
	18, // 3: medallion.terminal.v1.DataResponse.table:type_name -> medallion.terminal.v1.TablePayload
	19, // 4: medallion.terminal.v1.DataResponse.metric:type_name -> medallion.terminal.v1.MetricPayload
	20, // 5: medallion.terminal.v1.DataResponse.gauge:type_name -> medallion.terminal.v1.GaugePayload
	21, // 6: medallion.terminal.v1.DataResponse.heatmap:type_name -> medallion.terminal.v1.HeatmapPayload
	22, // 7: medallion.terminal.v1.DataResponse.events:type_name -> medallion.terminal.v1.EventPayload
	23, // 8: medallion.terminal.v1.DataResponse.distribution:type_name -> medallion.terminal.v1.DistributionPayload
	24, // 9: medallion.terminal.v1.DataResponse.text:type_name -> medallion.terminal.v1.TextPayload
	25, // 10: medallion.terminal.v1.DataResponse.orderbook:type_name -> medallion.terminal.v1.OrderBookPayload
	26, // 11: medallion.terminal.v1.DataResponse.paired_grid:type_name -> medallion.terminal.v1.PairedGridPayload
	27, // 12: medallion.terminal.v1.DataResponse.embed:type_name -> medallion.terminal.v1.EmbedPayload
	28, // 13: medallion.terminal.v1.DataResponse.assets:type_name -> medallion.terminal.v1.AssetCatalogPayload
	29, // 14: medallion.terminal.v1.DataResponse.object:type_name -> medallion.terminal.v1.ObjectPayload
	30, // 15: medallion.terminal.v1.DataResponse.graph:type_name -> medallion.terminal.v1.GraphPayload
	31, // 16: medallion.terminal.v1.DataResponse.repository:type_name -> medallion.terminal.v1.RepositoryPayload
	32, // 17: medallion.terminal.v1.DataResponse.records:type_name -> medallion.terminal.v1.RecordSetPayload
	33, // 18: medallion.terminal.v1.DataResponse.geo:type_name -> medallion.terminal.v1.GeoPayload
	34, // 19: medallion.terminal.v1.DataResponse.media:type_name -> medallion.terminal.v1.MediaPayload
	35, // 20: medallion.terminal.v1.DataResponse.conversation:type_name -> medallion.terminal.v1.ConversationPayload
	36, // 21: medallion.terminal.v1.DataResponse.json:type_name -> google.protobuf.Value
	7,  // 22: medallion.terminal.v1.ListSourcesResponse.sources:type_name -> medallion.terminal.v1.Source
	1,  // 23: medallion.terminal.v1.Source.shape:type_name -> medallion.terminal.v1.Shape
	8,  // 24: medallion.terminal.v1.Source.params:type_name -> medallion.terminal.v1.SourceParam
	0,  // 25: medallion.terminal.v1.SourceParam.type:type_name -> medallion.terminal.v1.ParamType
	37, // 26: medallion.terminal.v1.GenerateRequest.context:type_name -> medallion.terminal.v1.Context
	38, // 27: medallion.terminal.v1.GenerateRequest.current_widgets:type_name -> medallion.terminal.v1.Widget
	39, // 28: medallion.terminal.v1.GenerateResponse.actions:type_name -> medallion.terminal.v1.WidgetAction
	37, // 29: medallion.terminal.v1.GenerateResponse.context:type_name -> medallion.terminal.v1.Context
	40, // 30: medallion.terminal.v1.ActionRequest.params:type_name -> google.protobuf.Struct
	2,  // 31: medallion.terminal.v1.ActionResponse.status:type_name -> medallion.terminal.v1.ActionStatus
	40, // 32: medallion.terminal.v1.ActionResponse.data:type_name -> google.protobuf.Struct
	2,  // 33: medallion.terminal.v1.ActionUpdate.status:type_name -> medallion.terminal.v1.ActionStatus
	40, // 34: medallion.terminal.v1.ActionUpdate.data:type_name -> google.protobuf.Struct
	3,  // 35: medallion.terminal.v1.TerminalService.Get:input_type -> medallion.terminal.v1.DataRequest
	3,  // 36: medallion.terminal.v1.TerminalService.Stream:input_type -> medallion.terminal.v1.DataRequest
	5,  // 37: medallion.terminal.v1.TerminalService.ListSources:input_type -> medallion.terminal.v1.ListSourcesRequest
	9,  // 38: medallion.terminal.v1.TerminalService.Generate:input_type -> medallion.terminal.v1.GenerateRequest
	11, // 39: medallion.terminal.v1.TerminalService.SubmitAction:input_type -> medallion.terminal.v1.ActionRequest
	13, // 40: medallion.terminal.v1.TerminalService.WatchAction:input_type -> medallion.terminal.v1.ActionWatchRequest
	4,  // 41: medallion.terminal.v1.TerminalService.Get:output_type -> medallion.terminal.v1.DataResponse
	4,  // 42: medallion.terminal.v1.TerminalService.Stream:output_type -> medallion.terminal.v1.DataResponse
	6,  // 43: medallion.terminal.v1.TerminalService.ListSources:output_type -> medallion.terminal.v1.ListSourcesResponse
	10, // 44: medallion.terminal.v1.TerminalService.Generate:output_type -> medallion.terminal.v1.GenerateResponse
	12, // 45: medallion.terminal.v1.TerminalService.SubmitAction:output_type -> medallion.terminal.v1.ActionResponse
	14, // 46: medallion.terminal.v1.TerminalService.WatchAction:output_type -> medallion.terminal.v1.ActionUpdate
	41, // [41:47] is the sub-list for method output_type
	35, // [35:41] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_medallion_terminal_v1_terminal_proto_init() }
func file_medallion_terminal_v1_terminal_proto_init() {
	if File_medallion_terminal_v1_terminal_proto != nil {
		return
	}
	file_medallion_terminal_v1_shapes_proto_init()
	file_medallion_terminal_v1_template_proto_init()
	file_medallion_terminal_v1_terminal_proto_msgTypes[1].OneofWrappers = []any{
		(*DataResponse_Timeseries)(nil),
		(*DataResponse_Candles)(nil),
		(*DataResponse_Table)(nil),
		(*DataResponse_Metric)(nil),
		(*DataResponse_Gauge)(nil),
		(*DataResponse_Heatmap)(nil),
		(*DataResponse_Events)(nil),
		(*DataResponse_Distribution)(nil),
		(*DataResponse_Text)(nil),
		(*DataResponse_Orderbook)(nil),
		(*DataResponse_PairedGrid)(nil),
		(*DataResponse_Embed)(nil),
		(*DataResponse_Assets)(nil),
		(*DataResponse_Object)(nil),
		(*DataResponse_Graph)(nil),
		(*DataResponse_Repository)(nil),
		(*DataResponse_Records)(nil),
		(*DataResponse_Geo)(nil),
		(*DataResponse_Media)(nil),
		(*DataResponse_Conversation)(nil),
		(*DataResponse_Json)(nil),
	}
	file_medallion_terminal_v1_terminal_proto_msgTypes[9].OneofWrappers = []any{}
	file_medallion_terminal_v1_terminal_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_medallion_terminal_v1_terminal_proto_rawDesc), len(file_medallion_terminal_v1_terminal_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_medallion_terminal_v1_terminal_proto_goTypes,
		DependencyIndexes: file_medallion_terminal_v1_terminal_proto_depIdxs,
		EnumInfos:         file_medallion_terminal_v1_terminal_proto_enumTypes,
		MessageInfos:      file_medallion_terminal_v1_terminal_proto_msgTypes,
	}.Build()
	File_medallion_terminal_v1_terminal_proto = out.File
	file_medallion_terminal_v1_terminal_proto_goTypes = nil
	file_medallion_terminal_v1_terminal_proto_depIdxs = nil
}
