"""The declared protobuf floor must cover the gencode this package ships.

Every generated ``*_pb2`` module calls ``ValidateProtobufRuntimeVersion`` at
import time, and protobuf raises ``VersionError`` when the installed runtime is
older than the plugin release that generated the module. The ``protobuf``
requirement in ``pyproject.toml`` is only honest when its floor is at least the
gencode version stamped into every generated module under ``src``.
"""

from __future__ import annotations

import ast
import re
import tomllib
from pathlib import Path

import pytest

PROJECT = Path(__file__).resolve().parents[1]
GENERATED = sorted((PROJECT / "src").rglob("*_pb2.py"))
REQUIREMENT_NAME = re.compile(r"[A-Za-z0-9._-]+")
PROTOBUF_FLOOR = re.compile(r"protobuf>=([0-9]+)\.([0-9]+)\.([0-9]+)")


def gencode_version(path: Path) -> tuple[int, int, int]:
    """Return the major, minor, and patch a generated module validates."""
    calls = [
        node
        for node in ast.walk(ast.parse(path.read_text(), filename=str(path)))
        if isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and node.func.attr == "ValidateProtobufRuntimeVersion"
    ]
    assert len(calls) == 1, f"{path} must validate exactly one protobuf runtime version"
    # Arguments: domain, major, minor, patch, suffix, location.
    major, minor, patch = (ast.literal_eval(arg) for arg in calls[0].args[1:4])
    assert all(isinstance(part, int) for part in (major, minor, patch)), path
    return major, minor, patch


def declared_floor() -> tuple[int, int, int]:
    """Return the protobuf floor from the core ``[project].dependencies``."""
    with (PROJECT / "pyproject.toml").open("rb") as file:
        dependencies = tomllib.load(file)["project"]["dependencies"]
    requirements = [
        requirement
        for requirement in dependencies
        if (name := REQUIREMENT_NAME.match(requirement)) and name.group(0) == "protobuf"
    ]
    assert len(requirements) == 1, f"expected one protobuf requirement: {requirements}"
    match = PROTOBUF_FLOOR.fullmatch(requirements[0])
    assert match is not None, f"expected protobuf>=MAJOR.MINOR.PATCH: {requirements[0]}"
    major, minor, patch = (int(part) for part in match.groups())
    return major, minor, patch


def test_generated_modules_are_discovered() -> None:
    names = {path.relative_to(PROJECT / "src").as_posix() for path in GENERATED}
    assert {"temporaless/v1/temporaless_pb2.py", "buf/validate/validate_pb2.py"} <= names


@pytest.mark.parametrize(
    "path", GENERATED, ids=[path.relative_to(PROJECT).as_posix() for path in GENERATED]
)
def test_declared_protobuf_floor_covers_gencode(path: Path) -> None:
    generated = gencode_version(path)
    floor = declared_floor()
    assert floor >= generated, (
        f"pyproject.toml declares protobuf>={'.'.join(map(str, floor))}, but {path.name} "
        f"was generated by protobuf {'.'.join(map(str, generated))}; importing it on an "
        "older runtime raises VersionError, so raise the floor to the gencode version"
    )
